/// <reference types="vitest/config" />
import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import path from 'node:path'

export default defineConfig(({ mode }) => {
  // Dev proxy target: set VITE_API_PROXY_TARGET in frontend/.env.local
  // (generated by scripts/setup_local_env.sh from CloudFormation outputs).
  const env = loadEnv(mode, __dirname, '')
  const apiTarget = env.VITE_API_PROXY_TARGET || env.VITE_API_GATEWAY_URL || ''
  const proxyEntry = { target: apiTarget, changeOrigin: true, secure: true }

  return {
  plugins: [react(), tailwindcss()],
  define: {
    global: 'globalThis',
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    port: 3000,
    proxy: apiTarget ? {
      '^/dashboard/': proxyEntry,
      '^/coach/': proxyEntry,
      '^/config/': proxyEntry,
      '^/preferences': {
        ...proxyEntry,
        // Skip SPA navigation reloads: only proxy fetch/XHR requests (which include Authorization or accept JSON).
        bypass: (req) => {
          const accept = req.headers['accept'] ?? '';
          if (typeof accept === 'string' && accept.includes('text/html')) {
            return req.url ?? null;
          }
          return null;
        },
      },
      '^/health/': proxyEntry,
      '^/oauth/': proxyEntry,
    } : undefined,
  },
  build: {
    outDir: 'dist',
    sourcemap: false,
    chunkSizeWarningLimit: 600,
    rollupOptions: {
      output: {
        // Split only the heavy isolated libs that don't depend on React internals.
        // Keep React, React DOM, React Router, lucide, framer-motion in the main
        // bundle to avoid execution-order bugs across cross-chunk imports.
        manualChunks(id) {
          if (id.includes('node_modules')) {
            if (id.includes('recharts') || id.includes('d3-')) return 'recharts';
            if (id.includes('amazon-cognito')) return 'cognito';
          }
        },
      },
    },
  },
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: './src/test/setup.ts',
  },
  }
})
