"""
Content Generator Lambda Function

Generates enhanced content using Bedrock AI and AgentCore Memory.
Integrates with Strands Agents for intelligent content generation.
"""

import json
import os
import logging
from typing import Dict, Any, Optional, List
import boto3
from botocore.exceptions import ClientError
import sys
import asyncio
from datetime import datetime, timezone
from decimal import Decimal

# Add src directory to path for agent imports
sys.path.insert(0, '/opt/python')  # Lambda layer path

# Import LLM configuration
try:
    from config.llm_config import llm_config, get_bedrock_model_id, get_bedrock_params
except ImportError:
    # Fallback for development
    def get_bedrock_model_id():
        import os
        return os.environ.get('BEDROCK_MODEL_ID', 'global.anthropic.claude-sonnet-4-5-20250929-v1:0')
    def get_bedrock_params():
        return {
            'modelId': get_bedrock_model_id(),
            'body': {
                'anthropic_version': 'bedrock-2023-05-31',
                'max_tokens': 1200,
                'temperature': 0.7
            }
        }

# Import prompt management system
def get_bedrock_content_generation_prompt():
    """
    Get a simple, effective prompt for Bedrock fallback
    
    This is a lightweight fallback prompt - the full detailed prompt is in AgentCore agents.
    """
    return """Tu es un assistant de génération de contenu pour Strava AI Boost.

Ton rôle : Créer des titres et descriptions motivants pour des activités sportives en français.

Style :
- Technique mais accessible
- Motivant avec des éléments fun
- Emojis stratégiques (🚀💪⚡🔥🎯🏃‍♂️)
- Expressions percutantes : "Ça déchire !", "Machine bien huilée", "Objectif atomisé !"

Format de sortie JSON :
{
  "title": "Titre motivant (max 50 caractères)",
  "description": "Description technique et fun\\n\\n@Generated by Strava AI Boost (Fallback Mode)",
  "confidence": 0.8
}

IMPORTANT: Toujours terminer la description par "@Generated by Strava AI Boost (Fallback Mode)" sur une nouvelle ligne."""

logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Initialize AWS clients with region
REGION = os.environ.get('AWS_REGION', 'eu-west-1')
bedrock = boto3.client('bedrock-runtime', region_name=REGION)
dynamodb = boto3.resource('dynamodb', region_name=REGION)
secretsmanager = boto3.client('secretsmanager', region_name=REGION)

# Environment variables
ACTIVITIES_TABLE = os.environ.get('ACTIVITIES_TABLE', 'strava-ai-boost-activities')
USER_CONFIG_TABLE = os.environ.get('USER_CONFIG_TABLE', 'strava-ai-boost-user-configuration')
COACHING_SESSIONS_TABLE = os.environ.get('COACHING_SESSIONS_TABLE', 'campus-coaching-sessions')
STRAVA_OAUTH_SECRET = os.environ.get('STRAVA_OAUTH_SECRET', 'strava-ai-boost-oauth-tokens')
CAMPUS_COACH_SECRET = os.environ.get('CAMPUS_COACH_SECRET', 'strava-ai-boost-campus-coach-credentials')
AWS_REGION = os.environ.get('AWS_REGION', 'eu-west-1')


def handler(event: Dict[str, Any], context: Any) -> Dict[str, Any]:
    """
    Lambda handler for content generation
    
    Uses Strands Agent with AgentCore Memory for personalized content generation
    """
    try:
        # Log the incoming event for debugging
        logger.info(f"Content generator received event: {json.dumps(event, default=str)}")
        
        activity_id = event.get('activity_id')
        user_id = event.get('user_id')
        
        if not activity_id or not user_id:
            logger.error(f"Missing parameters - activity_id: {activity_id}, user_id: {user_id}")
            raise ValueError("Missing required parameters: activity_id, user_id")
        
        logger.info(f"Generating content for activity {activity_id}, user {user_id}")
        
        # Retrieve ALL activity data from DynamoDB (stored by ActivityFetcher)
        activity_data_full = retrieve_activity_data_from_dynamodb(activity_id)
        
        if not activity_data_full:
            raise ValueError(f"Activity data not found in DynamoDB for activity {activity_id}")
        
        # Extract components from stored data
        activity_data = activity_data_full.get('activity_data', {})
        streams_compressed = activity_data_full.get('streams_compressed')  # Already compressed in DynamoDB
        athlete_stats = activity_data_full.get('athlete_stats')
        athlete_profile = activity_data_full.get('athlete_profile')
        gear_details = activity_data_full.get('gear_details')
        intervals_icu_data = activity_data_full.get('intervals_icu_data')
        
        logger.info(f"Retrieved activity data from DynamoDB - distance: {activity_data.get('distance')}, type: {activity_data.get('sport_type')}")
        
        # Get user configuration and active modules
        user_config = get_user_configuration(user_id)
        active_modules = get_active_modules(user_config)
        
        # Build user_profile from configuration for personalization
        user_profile = build_user_profile_from_config(user_config)
        if user_profile:
            logger.info(f"User profile loaded for personalization: {user_profile.get('sport_approach')}")
        else:
            logger.info("No user profile configured, using default generation")
        
        # Streams are already compressed in DynamoDB for long activities
        if streams_compressed:
            logger.info(f"✅ Using pre-compressed streams: {streams_compressed.get('compression_ratio', 'N/A')}")
        
        # Extract Enduraw Report from activity description if available
        enduraw_data = extract_enduraw_report(activity_data)
        if enduraw_data:
            logger.info(f"Enduraw Report detected: {enduraw_data['metrics']}")
        
        # Apply module-specific processing (no streams_data needed)
        enhanced_modules = apply_module_processing(
            activity_data, None, user_id, active_modules
        )
        
        # Generate enhanced content using Strands Agent with user_profile
        enhanced_content = generate_enhanced_content_with_agent(
            activity_data, 
            streams_compressed,  # Pass compressed 30s blocks instead of raw streams
            user_id, 
            enhanced_modules,
            user_profile,  # Pass user_profile to agent
            athlete_stats,  # Pass athlete stats
            athlete_profile,  # Pass athlete profile
            gear_details,  # Pass gear details
            enduraw_data,  # Pass extracted Enduraw data
            intervals_icu_data  # Pass Intervals.icu data
        )
        
        # Store generated content
        store_generated_content(activity_id, enhanced_content)
        
        return {
            'statusCode': 200,
            'activity_id': activity_id,
            'user_id': user_id,
            'enhanced_content': enhanced_content,
            'modules_applied': [m['name'] for m in enhanced_modules]
        }
        
    except Exception as e:
        logger.error(f"Content generation error: {str(e)}")
        return {
            'statusCode': 500,
            'error': str(e),
            'activity_id': event.get('activity_id'),
            'user_id': event.get('user_id')
        }


def _parse_pace_mmss(pace_str: str) -> float:
    """Convert mm:ss pace string to float minutes. E.g. '5:45' -> 5.75"""
    try:
        parts = str(pace_str).split(':')
        if len(parts) == 2:
            return int(parts[0]) + int(parts[1]) / 60.0
        return float(pace_str)
    except (ValueError, TypeError):
        return 0.0


def _classify_by_pace_zones(avg_pace: float, pace_std: float, pace_range: float,
                            pace_zones: Dict[str, Any]) -> Optional[Dict[str, str]]:
    """
    Classify workout by matching average pace against user-configured pace zones.
    Returns {'type': ..., 'label': ...} if a zone matches, None otherwise.
    Only used when pace variability is low (not intervals).
    """
    # Zone definitions: key -> (type_name, label_fr)
    zone_labels = {
        'recovery': ('recovery_run', 'Recup / Recovery'),
        'ef': ('steady_easy_run', 'Endurance Fondamentale'),
        'tempo': ('tempo', 'Tempo'),
        'sweet_spot': ('sweet_spot', 'Sweet Spot'),
        'seuil_60': ('threshold_60', 'Seuil 60'),
        'seuil_30': ('threshold_30', 'Seuil 30'),
        'allure_marathon': ('marathon_pace', 'Allure Marathon'),
        'allure_semi': ('half_marathon_pace', 'Allure Semi'),
        'interval': ('intervals', 'Intervalles / VMA'),
    }

    best_match = None
    best_distance = float('inf')

    for zone_key, zone_val in pace_zones.items():
        if not isinstance(zone_val, dict):
            continue
        zone_min = _parse_pace_mmss(zone_val.get('min', '0'))
        zone_max = _parse_pace_mmss(zone_val.get('max', '0'))
        if zone_min <= 0 or zone_max <= 0:
            continue

        # Ensure min <= max (min pace = fastest = lower number, max pace = slowest = higher number)
        slow_pace = max(zone_min, zone_max)
        fast_pace = min(zone_min, zone_max)

        if fast_pace <= avg_pace <= slow_pace:
            # Direct match — compute distance to zone midpoint
            midpoint = (fast_pace + slow_pace) / 2
            distance = abs(avg_pace - midpoint)
            if distance < best_distance:
                best_distance = distance
                type_name, label_fr = zone_labels.get(zone_key, (zone_key, zone_key.replace('_', ' ').title()))
                best_match = {'type': type_name, 'label': label_fr}

    if best_match:
        logger.info(f"Pace zone match: avg_pace={avg_pace:.2f} -> {best_match['label']}")
    return best_match


def classify_workout_from_streams(blocks: List[Dict[str, Any]],
                                  pace_zones: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    Classify the workout type based on pace variability across blocks.
    Uses user-configured pace zones when available, falls back to statistical heuristics.
    Filters warmup/cooldown outliers using IQR.
    Returns classification with type and stats for the agent.
    """
    all_paces = [b.get('pace_min_km', 0) for b in blocks if 0 < b.get('pace_min_km', 0) < 15]
    valid_hrs = [b.get('hr_bpm', 0) for b in blocks if b.get('hr_bpm', 0) > 0]

    if len(all_paces) < 3:
        return {'type': 'unknown', 'confidence': 0}

    # Filter outliers using IQR (removes warmup/cooldown/stop artifacts)
    sorted_paces = sorted(all_paces)
    q1_idx = len(sorted_paces) // 4
    q3_idx = 3 * len(sorted_paces) // 4
    q1 = sorted_paces[q1_idx]
    q3 = sorted_paces[q3_idx]
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    core_paces = [p for p in all_paces if lower_bound <= p <= upper_bound]

    if len(core_paces) < 3:
        core_paces = all_paces  # fallback if too many filtered

    avg_pace = sum(core_paces) / len(core_paces)
    pace_std = (sum((p - avg_pace) ** 2 for p in core_paces) / len(core_paces)) ** 0.5
    pace_range = max(core_paces) - min(core_paces)
    avg_hr = sum(valid_hrs) / len(valid_hrs) if valid_hrs else 0
    hr_std = (sum((h - avg_hr) ** 2 for h in valid_hrs) / len(valid_hrs)) ** 0.5 if valid_hrs else 0

    # Step 1: Detect intervals by variability (regardless of pace zones)
    if pace_std > 0.6 and pace_range > 2.0:
        workout_type = 'intervals'
        label = 'Fractionne / Intervalles'
    elif pace_std > 0.40:
        # Check if it's a progression (pace decreasing over time)
        first_third = core_paces[:len(core_paces)//3]
        last_third = core_paces[-(len(core_paces)//3):]
        if first_third and last_third:
            avg_first = sum(first_third) / len(first_third)
            avg_last = sum(last_third) / len(last_third)
            if avg_first - avg_last > 0.5:
                workout_type = 'progression'
                label = 'Sortie progressive (negative split)'
            else:
                workout_type = 'steady_easy_run'
                label = 'Endurance fondamentale (allure legerement variable)'
        else:
            workout_type = 'steady_easy_run'
            label = 'Endurance fondamentale (allure legerement variable)'
    else:
        # Step 2: Steady effort — use pace zones if configured
        zone_match = _classify_by_pace_zones(avg_pace, pace_std, pace_range, pace_zones) if pace_zones else None

        if zone_match:
            workout_type = zone_match['type']
            label = zone_match['label']
        else:
            # Fallback: statistical heuristic
            if pace_std < 0.40:
                workout_type = 'steady_easy_run'
                label = 'Endurance fondamentale (allure reguliere)'
            else:
                workout_type = 'tempo'
                label = 'Tempo / Allure soutenue'

    classification = {
        'type': workout_type,
        'label': label,
        'avg_pace_min_km': round(avg_pace, 2),
        'pace_std_filtered': round(pace_std, 2),
        'pace_range_filtered': round(pace_range, 2),
        'blocks_total': len(all_paces),
        'blocks_core': len(core_paces),
        'avg_hr': round(avg_hr) if avg_hr else None,
        'hr_std': round(hr_std, 1) if hr_std else None,
        'pace_zones_used': pace_zones is not None,
    }

    logger.info(f"Workout classification: {workout_type} (std={pace_std:.2f}, range={pace_range:.2f}, core={len(core_paces)}/{len(all_paces)}, zones={'yes' if pace_zones else 'no'}) -> {label}")
    return classification


def detect_workout_phases(streams_compressed: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    Pre-compute workout phases from compressed blocks.
    Groups consecutive blocks with similar pace into phases (warmup, tempo, intervals, cooldown).
    Uses adaptive tolerance based on workout variability to avoid over-splitting steady runs.
    Returns a compact summary the agent can easily match against Campus Coach sessions.
    """
    if not streams_compressed:
        return []

    blocks = streams_compressed.get('blocks', [])
    if not blocks:
        return []

    # Compute pace variability with IQR filtering (same as classify_workout_from_streams)
    all_paces = [b.get('pace_min_km', 0) for b in blocks if 0 < b.get('pace_min_km', 0) < 15]
    if len(all_paces) < 3:
        return []

    sorted_paces = sorted(all_paces)
    q1 = sorted_paces[len(sorted_paces) // 4]
    q3 = sorted_paces[3 * len(sorted_paces) // 4]
    iqr = q3 - q1
    core_paces = [p for p in all_paces if (q1 - 1.5 * iqr) <= p <= (q3 + 1.5 * iqr)]
    if len(core_paces) < 3:
        core_paces = all_paces

    avg_core = sum(core_paces) / len(core_paces)
    pace_std = (sum((p - avg_core) ** 2 for p in core_paces) / len(core_paces)) ** 0.5

    # Adaptive tolerance: wider for steady runs, tighter for intervals
    # Steady run (std < 0.35): tolerance 1.0 min/km -> groups everything into ~1-3 phases
    # Intervals (std > 0.6): tolerance 0.3 min/km -> detects fast/slow alternation
    if pace_std < 0.35:
        tolerance = 1.0
    elif pace_std < 0.6:
        tolerance = 0.7
    else:
        tolerance = 0.3

    # Group consecutive blocks with similar pace
    phases = []
    current_phase = None

    for block in blocks:
        pace = block.get('pace_min_km', 0)
        hr = block.get('hr_bpm', 0)
        duration = block.get('duration_s', 30)

        if pace <= 0 or pace > 15:  # Skip stopped/invalid blocks
            continue

        if current_phase is None:
            current_phase = {'paces': [pace], 'hrs': [hr], 'duration_s': duration}
        elif abs(pace - (sum(current_phase['paces']) / len(current_phase['paces']))) < tolerance:
            # Same phase — similar pace within tolerance
            current_phase['paces'].append(pace)
            current_phase['hrs'].append(hr)
            current_phase['duration_s'] += duration
        else:
            # New phase — pace changed significantly
            phases.append(current_phase)
            current_phase = {'paces': [pace], 'hrs': [hr], 'duration_s': duration}

    if current_phase:
        phases.append(current_phase)

    # Summarize each phase
    summary = []
    for p in phases:
        avg_pace = sum(p['paces']) / len(p['paces'])
        avg_hr = sum(p['hrs']) / len(p['hrs']) if any(p['hrs']) else 0
        dur_min = p['duration_s'] / 60

        if dur_min < 0.5:  # Skip very short phases (<30s)
            continue

        pace_min = int(avg_pace)
        pace_sec = int((avg_pace - pace_min) * 60)

        summary.append({
            'duration_min': round(dur_min, 1),
            'avg_pace': f"{pace_min}:{pace_sec:02d}/km",
            'avg_hr': round(avg_hr) if avg_hr else None,
            'blocks_count': len(p['paces'])
        })

    logger.info(f"Detected {len(summary)} workout phases from {len(blocks)} blocks (tolerance={tolerance})")
    for s in summary:
        logger.info(f"  Phase: {s['duration_min']}min at {s['avg_pace']} (HR {s['avg_hr']})")

    return summary


def compress_streams_to_blocks(streams_data: Dict[str, Any], activity_data: Dict[str, Any], activity_id: str) -> Optional[Dict[str, Any]]:
    """
    Compress streams data into adaptive blocks based on activity duration
    
    This function:
    1. Checks if compressed data already exists in DynamoDB (cached)
    2. If not, compresses raw streams into adaptive blocks with avg pace/HR
    3. Adapts block duration based on activity length (less compression for short activities)
    4. Extracts key GPS points and reverse geocodes them to identify route landmarks
    5. Stores the compressed data in DynamoDB for future use
    6. Returns structured blocks ready for agent analysis
    
    Adaptive compression strategy (progressive):
    - < 60 min: 10s blocks (light compression, enables phase detection)
    - 60-120 min: 30s blocks (standard compression)
    - > 120 min: 30s blocks (standard compression)
    
    NO INTERPRETATION - just data compression. The agent will do the matching with Campus Coach.
    
    Args:
        streams_data: Raw streams from Strava (velocity_smooth, heartrate, time, distance, latlng)
        activity_data: Activity metadata for context
        activity_id: Activity ID for caching in DynamoDB
        
    Returns:
        Compressed streams as adaptive blocks + route landmarks, or None if no streams available
    """
    if not streams_data or not streams_data.get('velocity_smooth'):
        logger.info("No streams data available for compression")
        return None
    
    try:
        # Check if compressed data already exists in DynamoDB
        table = dynamodb.Table(ACTIVITIES_TABLE)
        response = table.get_item(Key={'activity_id': activity_id})
        
        if 'Item' in response and response['Item'].get('streams_analysis_json'):
            logger.info("✅ Using cached compressed streams from DynamoDB")
            cached_data = json.loads(response['Item']['streams_analysis_json'])
            return cached_data
        
        logger.info("No cached data found, compressing streams with adaptive blocks...")
        
        # Extract key streams
        velocity = streams_data.get('velocity_smooth', {}).get('data', [])
        heartrate = streams_data.get('heartrate', {}).get('data', [])
        time_series = streams_data.get('time', {}).get('data', [])
        distance = streams_data.get('distance', {}).get('data', [])
        latlng = streams_data.get('latlng', {}).get('data', [])  # GPS coordinates
        cadence_stream = streams_data.get('cadence', {}).get('data', [])
        watts_stream = streams_data.get('watts', {}).get('data', [])
        
        if not velocity or len(velocity) < 10:
            logger.info("Insufficient streams data for compression")
            return None
        
        # Calculate activity duration in minutes
        activity_duration_seconds = activity_data.get('elapsed_time', 0)
        activity_duration_minutes = activity_duration_seconds / 60
        
        # Adaptive block duration based on activity length
        # Strategy: Light compression for short activities (phase detection), standard for long
        if activity_duration_minutes < 60:
            block_duration = 10  # 10s blocks for short activities (enables workout phase detection)
            compression_level = "light"
            logger.info(f"Activity duration: {activity_duration_minutes:.1f} min → Light compression (10s blocks)")
        else:
            block_duration = 30  # 30s blocks for long activities
            compression_level = "standard"
        
        logger.info(f"Activity duration: {activity_duration_minutes:.1f} min → Block duration: {block_duration}s ({compression_level})")
        
        blocks = []
        
        i = 0
        while i < len(velocity):
            # Find all points in this 30s block
            start_time = time_series[i] if i < len(time_series) else i
            end_time = start_time + block_duration
            
            block_velocities = []
            block_hrs = []
            block_cadences = []
            block_watts = []
            block_end_idx = i
            
            # Collect all data points in this 30s window
            while block_end_idx < len(velocity):
                current_time = time_series[block_end_idx] if block_end_idx < len(time_series) else block_end_idx
                if current_time >= end_time:
                    break
                
                if velocity[block_end_idx] > 0:
                    block_velocities.append(velocity[block_end_idx])
                
                if block_end_idx < len(heartrate) and heartrate[block_end_idx]:
                    block_hrs.append(heartrate[block_end_idx])

                if block_end_idx < len(cadence_stream) and cadence_stream[block_end_idx]:
                    block_cadences.append(cadence_stream[block_end_idx])

                if block_end_idx < len(watts_stream) and watts_stream[block_end_idx]:
                    block_watts.append(watts_stream[block_end_idx])

                block_end_idx += 1
            
            # Calculate averages for this block
            if block_velocities:
                avg_velocity = sum(block_velocities) / len(block_velocities)
                avg_pace_min_km = 1000 / (avg_velocity * 60) if avg_velocity > 0 else 0
                avg_speed_kmh = avg_velocity * 3.6
                
                block = {
                    'time_min': round(start_time / 60, 1),
                    'duration_s': block_duration,
                    'pace_min_km': round(avg_pace_min_km, 2),
                    'speed_kmh': round(avg_speed_kmh, 1)
                }
                
                if block_hrs:
                    block['hr_bpm'] = int(sum(block_hrs) / len(block_hrs))

                if block_cadences:
                    block['cadence'] = int(sum(block_cadences) / len(block_cadences))

                if block_watts:
                    block['watts'] = int(sum(block_watts) / len(block_watts))

                blocks.append(block)
            
            # Move to next block
            i = block_end_idx if block_end_idx > i else i + 1
        
        # Extract route landmarks from Strava segments (no reverse geocoding)
        route_landmarks = []
        
        # Use Strava segment_efforts (reliable, free, already has city names)
        segment_efforts = activity_data.get('segment_efforts', [])
        if segment_efforts and len(segment_efforts) > 0:
            logger.info(f"Extracting route landmarks from {len(segment_efforts)} Strava segments...")
            
            # Sample key segments: start, middle, end
            # Sort by start_index to get chronological order
            sorted_segments = sorted(segment_efforts, key=lambda s: s.get('start_index', 0))
            
            # Select key segments (start, middle, end)
            key_indices = []
            if len(sorted_segments) >= 3:
                key_indices = [0, len(sorted_segments) // 2, len(sorted_segments) - 1]
            elif len(sorted_segments) == 2:
                key_indices = [0, 1]
            else:
                key_indices = [0]
            
            for idx in key_indices:
                segment_effort = sorted_segments[idx]
                segment = segment_effort.get('segment', {})
                
                segment_name = segment.get('name')
                city = segment.get('city')
                country = segment.get('country')
                
                if city or segment_name:
                    # Calculate position in activity
                    position = 'start' if idx == 0 else 'end' if idx == len(key_indices) - 1 else 'middle'
                    
                    landmark = {
                        'position': position,
                        'segment_name': segment_name,
                        'city': city,
                        'country': country,
                        'distance_m': segment_effort.get('distance', 0),
                        'elapsed_time_s': segment_effort.get('elapsed_time', 0),
                        'pr_rank': segment_effort.get('pr_rank'),
                    }
                    route_landmarks.append(landmark)
                    
                    logger.info(f"   ✅ Landmark at {position}: {segment_name} ({city}, {country})")
            
            logger.info(f"✅ Identified {len(route_landmarks)} route landmarks from Strava segments")
        else:
            logger.info("No Strava segments available for route landmarks")

        # Extract segment PRs (top 3 personal performances across ALL segments)
        segment_prs = []
        for se in segment_efforts:
            pr_rank = se.get('pr_rank')
            if pr_rank and pr_rank <= 3:
                segment_prs.append({
                    'name': se.get('segment', {}).get('name', ''),
                    'pr_rank': pr_rank,
                    'elapsed_time_s': se.get('elapsed_time', 0),
                    'distance_m': se.get('distance', 0),
                })

        # Build performance_summary from streams (more granular than Strava activity averages)
        performance_summary = {}
        if heartrate:
            performance_summary['avg_hr_bpm'] = int(sum(heartrate) / len(heartrate))
            performance_summary['max_hr_bpm'] = max(heartrate)
        if velocity:
            non_zero_vel = [v for v in velocity if v > 0]
            if non_zero_vel:
                avg_vel = sum(non_zero_vel) / len(non_zero_vel)
                performance_summary['avg_speed_kmh'] = round(avg_vel * 3.6, 1)
                performance_summary['max_speed_kmh'] = round(max(non_zero_vel) * 3.6, 1)
                performance_summary['avg_pace_min_km'] = round(1000 / (avg_vel * 60), 2) if avg_vel > 0 else None
        if cadence_stream:
            non_zero_cad = [c for c in cadence_stream if c > 0]
            if non_zero_cad:
                performance_summary['avg_cadence'] = int(sum(non_zero_cad) / len(non_zero_cad))
                performance_summary['max_cadence'] = max(non_zero_cad)
        if watts_stream:
            non_zero_watts = [w for w in watts_stream if w > 0]
            if non_zero_watts:
                performance_summary['avg_watts'] = int(sum(non_zero_watts) / len(non_zero_watts))
                performance_summary['max_watts'] = max(non_zero_watts)
        # Add Strava-provided scalar metrics
        for key in ('workout_type', 'suffer_score', 'pr_count', 'achievement_count'):
            val = activity_data.get(key)
            if val is not None:
                performance_summary[key] = val

        # Create compressed data structure
        compressed_data = {
            'blocks': blocks,
            'block_duration_s': block_duration,
            'compression_level': compression_level,
            'activity_duration_min': round(activity_duration_minutes, 1),
            'total_blocks': len(blocks),
            'total_duration_min': round(blocks[-1]['time_min'] if blocks else 0, 1),
            'compression_ratio': f"{len(velocity)} points → {len(blocks)} blocks ({block_duration}s blocks)",
            'route_landmarks': route_landmarks if route_landmarks else None,
            'performance_summary': performance_summary if performance_summary else None,
            'segment_prs': segment_prs if segment_prs else None
        }
        
        # Store compressed data in DynamoDB for future use
        table.update_item(
            Key={'activity_id': activity_id},
            UpdateExpression="SET streams_analysis_json = :data, updated_at = :updated",
            ExpressionAttributeValues={
                ':data': json.dumps(compressed_data),
                ':updated': datetime.utcnow().isoformat()
            }
        )
        
        logger.info(f"✅ Streams compressed and cached in DynamoDB")
        logger.info(f"   Compression: {len(velocity)} points → {len(blocks)} blocks ({block_duration}s each)")
        logger.info(f"   Total duration: {compressed_data['total_duration_min']:.1f} minutes")
        logger.info(f"   Route landmarks: {len(route_landmarks)} identified")
        logger.info(f"   Data size reduction: ~{100 * (1 - len(blocks) / len(velocity)):.0f}%")
        
        return compressed_data
        
    except Exception as e:
        logger.error(f"Failed to compress streams: {str(e)}")
        logger.error(f"   This is not critical - will proceed without compressed streams")
        return None


def extract_enduraw_report(activity_data: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """
    Extract Enduraw Report from activity description
    
    Enduraw adds a report to the description after 2 minutes:
    📈 𝗠𝘆 𝗘𝗻𝗱𝘂𝗿𝗮𝘄 𝗥𝗲𝗽𝗼𝗿𝘁 📈
    🏢 You climbed 53 floors today!
    Adjusted Pace: 𝟱:𝟯𝟮/km
    🏝️ Elevation (0.4% avg) cost you 𝟬'𝟬𝟰"/km.
    🌬️ Wind (17.2km/h) cost you 𝟬'𝟭𝟱"/km.
    ...
    """
    try:
        description = activity_data.get('description', '')
        
        if not description or '𝗘𝗻𝗱𝘂𝗿𝗮𝘄 𝗥𝗲𝗽𝗼𝗿𝘁' not in description:
            return None
        
        # Extract the Enduraw Report section
        import re
        
        # Find the Enduraw Report block
        enduraw_pattern = r'📈 𝗠𝘆 𝗘𝗻𝗱𝘂𝗿𝗮𝘄 𝗥𝗲𝗽𝗼𝗿𝘁 📈(.*?)(?:Try it now|$)'
        match = re.search(enduraw_pattern, description, re.DOTALL)
        
        if not match:
            return None
        
        report_text = match.group(1).strip()
        
        # Parse key metrics from report
        enduraw_data = {
            'report_available': True,
            'report_text': report_text,
            'metrics': {}
        }
        
        # Extract adjusted pace
        pace_match = re.search(r'Adjusted Pace:\s*([𝟬-𝟵]+):([𝟬-𝟵]+)/km', report_text)
        if pace_match:
            # Convert bold numbers to regular
            min_bold = pace_match.group(1).translate(str.maketrans('𝟬𝟭𝟮𝟯𝟰𝟱𝟲𝟳𝟴𝟵', '0123456789'))
            sec_bold = pace_match.group(2).translate(str.maketrans('𝟬𝟭𝟮𝟯𝟰𝟱𝟲𝟳𝟴𝟵', '0123456789'))
            enduraw_data['metrics']['adjusted_pace'] = f"{min_bold}:{sec_bold}/km"
        
        # Extract wind impact
        wind_match = re.search(r'Wind \(([0-9.]+)km/h\) cost you ([𝟬-𝟵]+)\'([𝟬-𝟵]+)"/km', report_text)
        if wind_match:
            wind_speed = wind_match.group(1)
            min_bold = wind_match.group(2).translate(str.maketrans('𝟬𝟭𝟮𝟯𝟰𝟱𝟲𝟳𝟴𝟵', '0123456789'))
            sec_bold = wind_match.group(3).translate(str.maketrans('𝟬𝟭𝟮𝟯𝟰𝟱𝟲𝟳𝟴𝟵', '0123456789'))
            enduraw_data['metrics']['wind_speed'] = f"{wind_speed}km/h"
            enduraw_data['metrics']['wind_cost'] = f"{min_bold}'{sec_bold}\"/km"
        
        # Extract elevation impact
        elev_match = re.search(r'Elevation \(([0-9.]+)% avg\) cost you ([𝟬-𝟵]+)\'([𝟬-𝟵]+)"/km', report_text)
        if elev_match:
            elev_pct = elev_match.group(1)
            min_bold = elev_match.group(2).translate(str.maketrans('𝟬𝟭𝟮𝟯𝟰𝟱𝟲𝟳𝟴𝟵', '0123456789'))
            sec_bold = elev_match.group(3).translate(str.maketrans('𝟬𝟭𝟮𝟯𝟰𝟱𝟲𝟳𝟴𝟵', '0123456789'))
            enduraw_data['metrics']['elevation_avg'] = f"{elev_pct}%"
            enduraw_data['metrics']['elevation_cost'] = f"{min_bold}'{sec_bold}\"/km"
        
        logger.info(f"Extracted Enduraw Report: {enduraw_data['metrics']}")
        return enduraw_data
        
    except Exception as e:
        logger.error(f"Failed to extract Enduraw Report: {str(e)}")
        return None


def retrieve_activity_data_from_dynamodb(activity_id: str) -> Optional[Dict[str, Any]]:
    """
    Retrieve complete activity data from DynamoDB
    
    This retrieves all data stored by ActivityFetcher to avoid Step Functions payload limits
    """
    try:
        table = dynamodb.Table(ACTIVITIES_TABLE)
        
        response = table.get_item(Key={'activity_id': activity_id})
        
        if 'Item' not in response:
            logger.error(f"Activity {activity_id} not found in DynamoDB")
            return None
        
        item = response['Item']
        
        # Parse JSON strings back to dictionaries
        activity_data = json.loads(item.get('activity_data_json', '{}'))
        # For long activities, streams are already compressed in DynamoDB
        streams_compressed = json.loads(item.get('streams_compressed_json', 'null')) if item.get('streams_compressed_json') else None
        athlete_stats = json.loads(item.get('athlete_stats_json', 'null')) if item.get('athlete_stats_json') else None
        athlete_profile = json.loads(item.get('athlete_profile_json', 'null')) if item.get('athlete_profile_json') else None
        gear_details = json.loads(item.get('gear_details_json', 'null')) if item.get('gear_details_json') else None
        intervals_icu_data = json.loads(item.get('intervals_icu_json', 'null')) if item.get('intervals_icu_json') else None

        # CRITICAL FIX: Convert numeric string values back to numbers
        # JSON serialization converts Decimal to string, we need to convert back
        def convert_numeric_strings(obj):
            """Recursively convert numeric strings to float/int"""
            if isinstance(obj, dict):
                return {k: convert_numeric_strings(v) for k, v in obj.items()}
            elif isinstance(obj, list):
                return [convert_numeric_strings(item) for item in obj]
            elif isinstance(obj, str):
                # Try to convert string to number if it looks numeric
                try:
                    # Check if it's an integer
                    if '.' not in obj and 'e' not in obj.lower():
                        return int(obj)
                    else:
                        return float(obj)
                except (ValueError, AttributeError):
                    return obj
            return obj
        
        # Apply conversion to all data
        activity_data = convert_numeric_strings(activity_data)
        streams_compressed = convert_numeric_strings(streams_compressed) if streams_compressed else None
        athlete_stats = convert_numeric_strings(athlete_stats) if athlete_stats else None
        athlete_profile = convert_numeric_strings(athlete_profile) if athlete_profile else None
        gear_details = convert_numeric_strings(gear_details) if gear_details else None
        intervals_icu_data = convert_numeric_strings(intervals_icu_data) if intervals_icu_data else None

        logger.info(f"Retrieved activity data from DynamoDB for {activity_id}")

        return {
            'activity_data': activity_data,
            'streams_compressed': streams_compressed,  # Pre-compressed from DynamoDB
            'athlete_stats': athlete_stats,
            'athlete_profile': athlete_profile,
            'gear_details': gear_details,
            'intervals_icu_data': intervals_icu_data
        }
        
    except Exception as e:
        logger.error(f"Failed to retrieve activity data from DynamoDB: {str(e)}")
        return None


def get_user_configuration(user_id: str) -> Dict[str, Any]:
    """Get user configuration from DynamoDB including module configuration"""
    try:
        table = dynamodb.Table(USER_CONFIG_TABLE)
        
        # Get user-specific configuration (now includes modules_config)
        response = table.get_item(Key={'user_id': user_id})
        user_config = response.get('Item', {
            'user_id': user_id,
            'modules_config': {},
            'enhancement_enabled': True
        })
        
        # Ensure modules_config exists
        if 'modules_config' not in user_config:
            user_config['modules_config'] = {}
            logger.warning(f"No modules_config found for user {user_id}, using defaults")
        else:
            logger.info(f"Loaded module configuration for user {user_id}: {list(user_config['modules_config'].keys())}")
        
        return user_config
            
    except Exception as e:
        logger.error(f"Failed to get user configuration: {str(e)}")
        return {
            'user_id': user_id,
            'modules_config': {},
            'enhancement_enabled': True
        }


def build_user_profile_from_config(user_config: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """
    Build user_profile from user configuration for agent personalization
    
    Extracts user preferences from DynamoDB config and formats them
    according to the agent's expected user_profile structure.
    """
    try:
        # Extract user preferences from config
        preferences = user_config.get('user_preferences', {})
        
        if not preferences:
            # No preferences configured, return None
            return None
        
        # Build user_profile according to agent prompt specification
        user_profile = {
            'age_range': preferences.get('age_range', '26-35'),
            'interests': preferences.get('interests', []),
            'sport_approach': preferences.get('sport_approach', 'health & wellness'),
            'content_preferences': {
                'length': preferences.get('content_length', 'medium'),
                'tone': preferences.get('content_tone', 'motivational & energetic'),
                'emoji_usage': preferences.get('emoji_usage', 'moderate'),
                'technical_detail': preferences.get('technical_detail', 'intermediate'),
                'language': preferences.get('content_language', 'french')
            }
        }

        # Add pace zones if configured
        pace_zones = preferences.get('pace_zones')
        if pace_zones:
            user_profile['pace_zones'] = pace_zones
            logger.info(f"Pace zones loaded: {list(pace_zones.keys())}")
        
        logger.info(f"Built user_profile: age={user_profile['age_range']}, approach={user_profile['sport_approach']}")
        logger.info(f"Content preferences: length={user_profile['content_preferences']['length']}, tone={user_profile['content_preferences']['tone']}, emoji={user_profile['content_preferences']['emoji_usage']}, technical={user_profile['content_preferences']['technical_detail']}")
        logger.info(f"Interests: {user_profile['interests']}")
        return user_profile
        
    except Exception as e:
        logger.error(f"Failed to build user_profile: {str(e)}")
        return None


def get_active_modules(user_config: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Get list of active modules for the user using module registry"""
    try:
        from modules import module_registry
        
        modules_config = user_config.get('modules_config', {})
        active_modules = []
        
        # Get available modules from registry
        available_modules = module_registry.get_available_modules()
        
        for module_id in available_modules:
            config = modules_config.get(module_id, {})
            if config.get('enabled', False):
                # Get module info from registry
                module_info = module_registry.get_module_info(module_id)
                if module_info:
                    active_modules.append({
                        'name': module_id,
                        'config': config,
                        'enabled': True,
                        'info': module_info
                    })
        
        logger.info(f"Found {len(active_modules)} active modules from registry")
        return active_modules
        
    except ImportError:
        logger.warning("Module registry not available, using fallback")
        # Fallback to original implementation
        modules_config = user_config.get('modules_config', {})
        active_modules = []
        
        logger.info(f"Checking modules_config: {list(modules_config.keys())}")
        
        for module_id, config in modules_config.items():
            logger.info(f"Module {module_id}: enabled={config.get('enabled', False)}")
            if config.get('enabled', False):
                active_modules.append({
                    'name': module_id,
                    'config': config,
                    'enabled': True
                })
        
        logger.info(f"Found {len(active_modules)} active modules (fallback)")
        return active_modules
        
    except Exception as e:
        logger.error(f"Failed to get active modules: {str(e)}")
        return []


def apply_module_processing(
    activity_data: Dict[str, Any],
    streams_data: Optional[Dict[str, Any]],
    user_id: str,
    modules: List[Dict[str, Any]]
) -> List[Dict[str, Any]]:
    """
    Apply module-specific processing using module registry
    
    Enhances modules with additional data (e.g., Campus Coach session matching)
    """
    enhanced_modules = []
    
    try:
        from modules import module_registry, ModuleConfig
        
        for module in modules:
            try:
                module_id = module['name']
                
                # Create module instance from registry
                config_data = module.get('config', {})
                module_config = ModuleConfig(
                    module_id=module_id,
                    enabled=module.get('enabled', False),
                    credentials=config_data.get('credentials'),
                    settings=config_data.get('settings', {})
                )
                
                module_instance = module_registry.create_module_instance(module_id, module_config)
                
                if module_instance:
                    # Process with module instance
                    enhanced_module = apply_module_instance_processing(
                        activity_data, streams_data, user_id, module, module_instance
                    )
                    enhanced_modules.append(enhanced_module)
                else:
                    # Fallback to legacy processing
                    enhanced_module = apply_legacy_module_processing(
                        activity_data, streams_data, user_id, module
                    )
                    enhanced_modules.append(enhanced_module)
                    
            except Exception as e:
                logger.error(f"Module {module.get('name', 'unknown')} processing failed: {str(e)}")
                # Include module with error info
                module_with_error = module.copy()
                module_with_error['processing_error'] = str(e)
                enhanced_modules.append(module_with_error)
    
    except ImportError:
        logger.warning("Module registry not available, using legacy processing")
        # Fallback to legacy processing for all modules
        for module in modules:
            try:
                enhanced_module = apply_legacy_module_processing(
                    activity_data, streams_data, user_id, module
                )
                enhanced_modules.append(enhanced_module)
            except Exception as e:
                logger.error(f"Legacy module {module.get('name', 'unknown')} processing failed: {str(e)}")
                module_with_error = module.copy()
                module_with_error['processing_error'] = str(e)
                enhanced_modules.append(module_with_error)
    
    return enhanced_modules


def apply_module_instance_processing(
    activity_data: Dict[str, Any],
    streams_data: Optional[Dict[str, Any]],
    user_id: str,
    module: Dict[str, Any],
    module_instance
) -> Dict[str, Any]:
    """Apply processing using module registry instance"""
    try:
        # Use asyncio to run the async module method
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        
        try:
            insight = loop.run_until_complete(
                module_instance.analyze_activity_with_timeout(activity_data, streams_data)
            )
            
            # Enhance module with insight results
            enhanced_module = module.copy()
            enhanced_module['insight'] = {
                'module_id': insight.module_id,
                'insights': insight.insights,
                'confidence': insight.confidence,
                'metadata': insight.metadata,
                'processing_time_ms': insight.processing_time_ms,
                'error_message': insight.error_message
            }
            
            logger.info(f"Module {module['name']} processed with confidence: {insight.confidence}")
            return enhanced_module
            
        finally:
            loop.close()
            
    except Exception as e:
        logger.error(f"Module instance processing error: {str(e)}")
        enhanced_module = module.copy()
        enhanced_module['processing_error'] = str(e)
        return enhanced_module


def apply_legacy_module_processing(
    activity_data: Dict[str, Any],
    streams_data: Optional[Dict[str, Any]],
    user_id: str,
    module: Dict[str, Any]
) -> Dict[str, Any]:
    """Apply legacy module processing for backward compatibility"""
    try:
        module_name = module['name']
        logger.info(f"🔧 Legacy processing for module: {module_name}, enabled: {module.get('enabled', False)}")
        
        if module_name == 'campus_coach' and module.get('enabled', False):
            # Apply Campus Coach session matching
            enhanced_module = apply_campus_coach_processing(
                activity_data, user_id, module
            )
            return enhanced_module
            
        elif module_name == 'enduraw' and module.get('enabled', False):
            # Enduraw processing (wait logic handled in webhook processor)
            return module
            
        else:
            # Other modules - pass through
            return module
            
    except Exception as e:
        logger.error(f"Legacy module {module.get('name', 'unknown')} processing failed: {str(e)}")
        module_with_error = module.copy()
        module_with_error['processing_error'] = str(e)
        return module_with_error


def apply_campus_coach_processing(
    activity_data: Dict[str, Any],
    user_id: str,
    module: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Apply Campus Coach session matching processing
    
    Retrieves recent Campus Coach sessions from DynamoDB.
    The intelligent matching and compliance analysis is done by the content generation agent
    using Claude Sonnet 4.5 with detailed stream analysis (pace, HR, intervals).
    """
    try:
        logger.info("Retrieving Campus Coach sessions for intelligent agent matching...")
        
        # Get activity details
        activity_date = activity_data.get('start_date_local', activity_data.get('start_date', ''))
        distance_km = activity_data.get('distance', 0) / 1000
        duration_min = activity_data.get('moving_time', 0) / 60
        activity_type = activity_data.get('type', '').lower()
        
        logger.info(f"Activity: {activity_type}, {distance_km:.1f}km, {duration_min:.0f}min, date: {activity_date}")
        
        # Get all recent Campus Coach sessions from DynamoDB
        sessions = get_recent_campus_sessions(activity_date)
        
        enhanced_module = module.copy()
        
        if sessions and len(sessions) > 0:
            logger.info(f"✅ Retrieved {len(sessions)} Campus Coach sessions for agent analysis")
            
            # Pass all sessions to the agent for intelligent matching
            # The agent will analyze:
            # - Strava streams (pace, heart rate, power, cadence)
            # - Campus Coach intervals (target pace, duration, repetitions)
            # - Compliance scoring (distance, duration, pace zones)
            # - Performance analysis (actual vs planned)
            enhanced_module['campus_coach_sessions'] = sessions
            enhanced_module['sessions_available'] = True
            enhanced_module['session_count'] = len(sessions)
            
            # Add activity context for agent matching (including title for semantic matching)
            enhanced_module['activity_context'] = {
                'date': activity_date,
                'distance_km': distance_km,
                'duration_min': duration_min,
                'type': activity_type,
                'title': activity_data.get('name', ''),  # Activity title can hint at session type (e.g., "EF", "Tempo", "Fractionné")
                'description': activity_data.get('description', '')  # Original description may contain session clues
            }
            
            logger.info(f"Campus Coach sessions will be analyzed by agent (activity title: '{activity_data.get('name', 'N/A')}')")
        else:
            logger.info("❌ No Campus Coach sessions available")
            enhanced_module['campus_coach_sessions'] = []
            enhanced_module['sessions_available'] = False
            enhanced_module['note'] = 'No recent Campus Coach sessions found'
        
        return enhanced_module
            
    except Exception as e:
        logger.error(f"Campus Coach processing error: {str(e)}")
        enhanced_module = module.copy()
        enhanced_module['campus_coach_sessions'] = []
        enhanced_module['sessions_available'] = False
        enhanced_module['error'] = str(e)
        return enhanced_module


def get_recent_campus_sessions(activity_date: str = None) -> List[Dict[str, Any]]:
    """Get Campus Coach sessions for the current week only (max 6)"""
    try:
        logger.info("🔍 Querying Campus Coach sessions from DynamoDB...")
        table = dynamodb.Table(COACHING_SESSIONS_TABLE)
        
        from datetime import datetime, timedelta
        if activity_date:
            try:
                act_dt = datetime.fromisoformat(activity_date.replace('Z', '+00:00'))
            except Exception:
                act_dt = datetime.utcnow()
        else:
            act_dt = datetime.utcnow()
        
        # Get sessions updated in the last 14 days (covers current + previous week)
        cutoff_date = (act_dt - timedelta(days=14)).isoformat()
        
        logger.info(f"Filtering sessions: updated_at >= '{cutoff_date}', status = 'À faire'")
        
        response = table.scan(
            FilterExpression='updated_at >= :cutoff AND #status = :status',
            ExpressionAttributeNames={'#status': 'status'},
            ExpressionAttributeValues={
                ':cutoff': cutoff_date,
                ':status': 'À faire'
            }
        )
        
        sessions = response.get('Items', [])
        logger.info(f"📊 Found {len(sessions)} 'À faire' sessions updated since {cutoff_date}")
        
        # Sort by updated_at DESC to get most recent sessions first
        sessions = sorted(sessions, key=lambda x: x.get('updated_at', ''), reverse=True)
        
        # Cap at 6 (typical max sessions per week)
        sessions = sessions[:6]
        
        for session in sessions:
            logger.info(f"  - {session.get('title', 'Unknown')} (week {session.get('week_number', '?')}, updated: {session.get('updated_at', '?')})")
        
        from decimal import Decimal
        def decimal_to_float(obj):
            if isinstance(obj, Decimal):
                return float(obj)
            elif isinstance(obj, dict):
                return {k: decimal_to_float(v) for k, v in obj.items()}
            elif isinstance(obj, list):
                return [decimal_to_float(item) for item in obj]
            return obj
        
        sessions = decimal_to_float(sessions)
        
        logger.info(f"✅ Retrieved {len(sessions)} Campus Coach sessions for agent matching")
        return sessions
        
    except Exception as e:
        logger.error(f"❌ Failed to retrieve Campus Coach sessions: {str(e)}")
        return []


def generate_enhanced_content_with_agent(
    activity_data: Dict[str, Any],
    streams_compressed: Optional[Dict[str, Any]],  # Compressed 30s blocks instead of raw streams
    user_id: str,
    modules: List[Dict[str, Any]],
    user_profile: Optional[Dict[str, Any]] = None,
    athlete_stats: Optional[Dict[str, Any]] = None,
    athlete_profile: Optional[Dict[str, Any]] = None,
    gear_details: Optional[Dict[str, Any]] = None,
    enduraw_data: Optional[Dict[str, Any]] = None,
    intervals_icu_data: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Generate enhanced content using Strands Agent with AgentCore Memory
    
    Uses actual AgentCore agent invocation via Bedrock Agent Runtime
    """
    try:
        logger.info("Generating content with AgentCore Content Generation Agent...")
        logger.info(f"Content generation mode: AgentCore (primary)")
        logger.info(f"User profile provided: {user_profile is not None}")
        logger.info(f"Enduraw data provided: {enduraw_data is not None}")
        
        # Use Bedrock AgentCore Runtime to invoke AgentCore Content Generation Agent
        # Try different client approaches for AgentCore invocation
        try:
            # First try the documented bedrock-agentcore client
            bedrock_agentcore_client = boto3.client('bedrock-agentcore', region_name=REGION)
        except Exception as e:
            logger.warning(f"bedrock-agentcore client not available: {str(e)}")
            try:
                # Fallback to bedrock-agent-runtime
                bedrock_agentcore_client = boto3.client('bedrock-agent-runtime', region_name=REGION)
            except Exception as e2:
                logger.error(f"No suitable AgentCore client available: {str(e2)}")
                # Fallback to direct Bedrock generation
                return generate_enhanced_content_fallback(
                    activity_data, streams_compressed, user_id, modules, user_profile
                )
        
        # Create session ID for this invocation (minimum 33 characters required)
        import uuid
        session_id = f"content-gen-{uuid.uuid4().hex}"  # UUID hex is 32 chars + prefix = 44 chars total
        
        # Extract Campus Coach sessions from modules if available
        campus_coach_sessions = None
        for module in modules:
            if module.get('name') == 'campus_coach':
                logger.info(f"🔍 Found Campus Coach module in enhanced_modules")
                if module.get('sessions_available'):
                    campus_coach_sessions = module.get('campus_coach_sessions', [])
                    logger.info(f"✅ Passing {len(campus_coach_sessions)} Campus Coach sessions to agent")
                    logger.info(f"   Activity context: {module.get('activity_context', {})}")
                else:
                    logger.warning("⚠️ Campus Coach module present but no sessions available")
                break
        
        if not campus_coach_sessions:
            logger.info("ℹ️ No Campus Coach sessions to pass to agent")
        
        # Pre-compute workout phases for the agent (compact summary instead of raw blocks)
        workout_phases = detect_workout_phases(streams_compressed) if streams_compressed else []
        route_landmarks = streams_compressed.get('route_landmarks', []) if streams_compressed else []

        # Classify workout type based on pace variability + user pace zones
        blocks = streams_compressed.get('blocks', []) if streams_compressed else []
        user_pace_zones = user_profile.get('pace_zones') if user_profile else None
        workout_classification = classify_workout_from_streams(blocks, pace_zones=user_pace_zones) if blocks else None

        # Also pass compressed blocks for fine-grained analysis if needed
        compressed_blocks = blocks

        # Clean activity_data to remove previous AI-generated content that could bias the agent
        clean_activity_data = {k: v for k, v in activity_data.items()
                               if k not in ('enhanced_description', 'enhanced_title', 'description',
                                            'processing_status', 'processing_error')}
        # Strip previous AI-generated description from the name if it contains our marker
        activity_name = clean_activity_data.get('name', '')
        if '@Generated by Strava AI Boost' in str(clean_activity_data.get('name', '')):
            clean_activity_data['name'] = 'Activity'  # Reset to generic

        # Build classification instruction for the agent
        classification_instruction = None
        if workout_classification and workout_classification.get('type') != 'unknown':
            wc_label = workout_classification.get('label', workout_classification['type'])
            classification_instruction = (
                f"CRITICAL INSTRUCTION — Workout type detected from GPS/HR stream analysis: {wc_label}. "
                f"You MUST generate a title and description that matches this workout type. "
                f"Do NOT use 'fractionné', 'intervalles', or 'interval' unless the classification type is 'intervals'. "
                f"Do NOT copy or reproduce the existing activity title — generate a completely new one based on the classification."
            )
            logger.info(f"Classification instruction: {classification_instruction}")

        # Prepare input for AgentCore Content Generation Agent
        agent_input = {
            'action': 'generate_content',
            'classification_instruction': classification_instruction,  # FIRST field — MUST be followed by agent
            'workout_classification': workout_classification,  # Detected workout type from streams
            'activity_data': clean_activity_data,  # Cleaned: no previous AI content
            'workout_phases': workout_phases,  # Compact phase summary for matching
            'compressed_blocks': compressed_blocks,  # Fine-grained 30s blocks if agent needs details
            'route_landmarks': route_landmarks,
            'athlete_stats': athlete_stats,
            'athlete_profile': athlete_profile,
            'gear_details': gear_details,
            'user_id': user_id,
            'user_profile': user_profile,
            'active_modules': modules,
            'campus_coach_session': campus_coach_sessions,
            'enduraw_data': enduraw_data,
            'intervals_icu_data': intervals_icu_data,
            'workout_type': activity_data.get('workout_type'),
            'use_memory': True,
            'personalization': True
        }
        
        logger.info(f"Agent input prepared - user_profile: {json.dumps(user_profile, default=str) if user_profile else 'None'}")
        
        # Get agent ARN from environment
        agent_arn = os.environ.get('CONTENT_GENERATION_AGENT_ARN', '')
        agent_name = os.environ.get('CONTENT_GENERATION_AGENT_NAME', 'content_gen')
        
        if not agent_arn:
            logger.error("CONTENT_GENERATION_AGENT_ARN environment variable not set")
            raise ValueError("AgentCore Content Generation Agent ARN not configured")
        
        logger.info(f"Invoking AgentCore Content Generation Agent: {agent_name} (ARN: {agent_arn})")
        
        # Prepare payload for AgentCore
        payload = json.dumps(agent_input).encode('utf-8')
        
        # Invoke AgentCore Content Generation Agent using correct API
        try:
            response = bedrock_agentcore_client.invoke_agent_runtime(
                agentRuntimeArn=agent_arn,
                runtimeSessionId=session_id,
                payload=payload
            )
        except Exception as invoke_error:
            logger.error(f"AgentCore agent invocation failed: {str(invoke_error)}")
            logger.error(f"Error type: {type(invoke_error).__name__}")
            # Go directly to fallback on any error
            return generate_enhanced_content_fallback(
                activity_data, streams_compressed, user_id, modules, user_profile
            )
        
        # Process streaming response from AgentCore
        completion = ""
        try:
            if "text/event-stream" in response.get("contentType", ""):
                # Handle streaming response
                for line in response["response"].iter_lines(chunk_size=10):
                    if line:
                        try:
                            line = line.decode("utf-8", errors='replace')  # Replace invalid UTF-8 with �
                        except Exception as decode_error:
                            logger.warning(f"UTF-8 decode error, skipping line: {decode_error}")
                            continue
                        if line.startswith("data: "):
                            line = line[6:]
                            completion += line
            elif response.get("contentType") == "application/json":
                # Handle standard JSON response
                content = []
                for chunk in response.get("response", []):
                    try:
                        content.append(chunk.decode('utf-8', errors='replace'))
                    except Exception as decode_error:
                        logger.warning(f"UTF-8 decode error in chunk: {decode_error}")
                        continue
                completion = ''.join(content)
            else:
                # Handle other content types
                completion = str(response.get("response", ""))
        except Exception as stream_error:
            logger.error(f"Error processing AgentCore response stream: {str(stream_error)}")
            return generate_enhanced_content_fallback(
                activity_data, streams_compressed, user_id, modules, user_profile
            )
        
        logger.info(f"AgentCore Content Generation Agent response length: {len(completion)}")
        logger.info(f"AgentCore response preview: {completion[:500]}...")
        
        # Parse agent response
        try:
            # First, try to parse the outer response structure
            outer_response = json.loads(completion)
            
            # Check if response is wrapped in a "response" field
            if 'response' in outer_response:
                response_text = outer_response['response']
                logger.info(f"Extracted response field, length: {len(response_text)}")
            else:
                response_text = completion
            
            # Try to extract JSON from response text (may be in markdown code block)
            import re
            # Remove markdown code blocks if present
            response_text = re.sub(r'```json\s*', '', response_text)
            response_text = re.sub(r'```\s*$', '', response_text)
            response_text = response_text.strip()
            
            # Now parse the actual content JSON
            json_match = re.search(r'\{.*\}', response_text, re.DOTALL)
            
            if json_match:
                agent_response = json.loads(json_match.group())
                
                # Handle both old and new response formats
                title = None
                description = None
                confidence = 0.8
                
                # Check for new format with generated_content
                if 'generated_content' in agent_response:
                    generated_content = agent_response['generated_content']
                    title = generated_content.get('title', 'Enhanced Activity')
                    description = generated_content.get('description', 'AI-enhanced description')
                    
                    # Extract confidence from content_metadata
                    if 'content_metadata' in agent_response:
                        confidence = agent_response['content_metadata'].get('confidence', 0.8)
                
                # Check for old format with direct title/description
                elif 'title' in agent_response and 'description' in agent_response:
                    title = agent_response.get('title', 'Enhanced Activity')
                    description = agent_response.get('description', 'AI-enhanced description')
                    confidence = agent_response.get('confidence', 0.8)
                
                if title and description:
                    # Post-process: validate title matches workout classification
                    if workout_classification and workout_classification.get('type') not in ('intervals', 'unknown', None):
                        import re as _re
                        interval_keywords = _re.compile(r'fractionn|interval|split|répétition', _re.IGNORECASE)
                        if interval_keywords.search(title):
                            wc_label = workout_classification.get('label', 'Activité')
                            # Extract emoji from original title if any
                            emojis = ''.join(c for c in title if ord(c) > 0x1F000)
                            if not emojis:
                                emojis = '🏃'
                            logger.warning(f"Title/classification mismatch: title='{title}' but classification='{workout_classification['type']}'. Fixing title.")
                            title = f"{emojis} {wc_label}"

                    # Add signature to description if not present (AgentCore mode - normal signature)
                    if not description.endswith('@Generated by Strava AI Boost'):
                        description += '\n\n@Generated by Strava AI Boost'
                    
                    # Extract additional metadata
                    style_elements = ['ai_generated']
                    patterns_detected = []
                    memory_used = False
                    expressions_avoided = []
                    
                    if 'content_metadata' in agent_response:
                        metadata = agent_response['content_metadata']
                        style_elements = [metadata.get('tone_used', 'ai_generated')]
                        patterns_detected = metadata.get('fun_elements_included', [])
                    
                    if 'memory_operations' in agent_response:
                        memory_ops = agent_response['memory_operations']
                        memory_used = memory_ops.get('retrieved', False) or memory_ops.get('stored', False)
                        expressions_avoided = memory_ops.get('expressions_avoided', [])
                    
                    enhanced_content = {
                        'title': title[:50],  # Limit title length
                        'description': description,
                        'style_elements': style_elements,
                        'confidence': confidence,
                        'modules_used': [m['name'] for m in modules],
                        'patterns_detected': patterns_detected,
                        'analysis_type': 'agentcore_memory',
                        'memory_used': memory_used,
                        'expressions_avoided': expressions_avoided
                    }
                    
                    logger.info(f"Content generated with confidence: {enhanced_content.get('confidence', 0.0)}")
                    logger.info(f"Content generation mode: AgentCore (successful)")
                    return enhanced_content
                else:
                    logger.warning("Invalid response structure from AgentCore agent")
                    return generate_enhanced_content_fallback(
                        activity_data, streams_compressed, user_id, modules
                    )
            else:
                logger.warning("Could not parse JSON from AgentCore agent response")
                return generate_enhanced_content_fallback(
                    activity_data, streams_compressed, user_id, modules
                )

        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse AgentCore agent response: {str(e)}")
            return generate_enhanced_content_fallback(
                activity_data, streams_compressed, user_id, modules
            )

    except Exception as e:
        logger.error(f"AgentCore Content Generation Agent invocation failed: {str(e)}")
        logger.info(f"Content generation mode: Switching to Bedrock fallback")

        # Check if this is a cold start or availability issue
        if "timeout" in str(e).lower() or "unavailable" in str(e).lower():
            logger.warning("Possible AgentCore agent cold start or availability issue")

        # Fallback to direct Bedrock generation
        return generate_enhanced_content_fallback(
            activity_data, streams_compressed, user_id, modules
        )


def generate_enhanced_content_fallback(
    activity_data: Dict[str, Any],
    streams_compressed: Optional[Dict[str, Any]],  # Compressed 30s blocks instead of raw streams
    user_id: str,
    modules: List[Dict[str, Any]],
    user_profile: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Fallback content generation using Bedrock directly
    
    Used when Strands Agent is not available
    """
    try:
        logger.info("Using fallback content generation...")
        logger.info(f"Content generation mode: Bedrock fallback (direct Claude Sonnet 4.5)")
        
        # Analyze streams data for effort patterns
        patterns = analyze_streams_data_fallback(streams_compressed, activity_data)
        
        # Extract module insights
        module_insights = extract_module_insights(modules)
        
        # Generate content with Bedrock directly
        enhanced_content = generate_with_bedrock_enhanced(
            activity_data, patterns, module_insights
        )
        
        logger.info(f"Content generation mode: Bedrock fallback (successful, confidence: {enhanced_content.get('confidence', 0.0)})")
        return enhanced_content
        
    except Exception as e:
        logger.error(f"Fallback content generation failed: {str(e)}")
        logger.error(f"Content generation mode: All methods failed, using basic fallback")
        # Return basic fallback content
        return {
            'title': f"Enhanced: {activity_data.get('name', 'Activity')}",
            'description': f"AI-enhanced description for {activity_data.get('type', 'activity')}\n\n@Generated by Strava AI Boost (Fallback Mode)",
            'style_elements': ['fallback'],
            'modules_used': [m['name'] for m in modules],
            'confidence': 0.5,
            'error': str(e)
        }


def analyze_streams_data_fallback(
    streams_compressed: Optional[Dict[str, Any]],  # Compressed 30s blocks instead of raw streams
    activity_data: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Fallback streams data analysis for effort patterns and heart rate zones
    
    Uses compressed 30s blocks to identify patterns
    """
    try:
        if not streams_compressed or not streams_compressed.get('blocks'):
            return analyze_basic_activity_patterns(activity_data)
        
        # Extract compressed blocks
        blocks = streams_compressed.get('blocks', [])
        
        patterns = []
        effort_zones = []
        intervals_count = 0
        
        # Analyze pace patterns for intervals using compressed blocks
        if blocks and len(blocks) > 10:
            # Simple interval detection based on pace variation
            pace_changes = []
            for i in range(1, len(blocks)):
                try:
                    prev_pace = float(blocks[i-1].get('pace_min_km', 0))
                    curr_pace = float(blocks[i].get('pace_min_km', 0))
                    
                    if prev_pace > 0 and curr_pace > 0:
                        # Calculate pace change (faster pace = lower number)
                        change = abs(curr_pace - prev_pace) / prev_pace
                        pace_changes.append(change)
                except (ValueError, TypeError, KeyError):
                    continue
            
            # Count significant pace changes (potential intervals)
            significant_changes = [c for c in pace_changes if c > 0.15]  # 15% pace change
            intervals_count = len(significant_changes) // 2  # Pairs of up/down changes
            
            if intervals_count > 3:
                patterns.append('interval_training')
            elif intervals_count > 0:
                patterns.append('fartlek')
            else:
                patterns.append('steady_effort')
        
        # Analyze heart rate zones from compressed blocks
        hr_values = [block.get('hr_bpm') for block in blocks if block.get('hr_bpm')]
        if hr_values:
            try:
                avg_hr = sum(hr_values) / len(hr_values)
                max_hr = max(hr_values)
                
                # Simple zone estimation (assuming max HR ~190 for average athlete)
                estimated_max_hr = 190
                hr_percentage = avg_hr / estimated_max_hr
                
                if hr_percentage < 0.6:
                    effort_zones.append('zone1')
                elif hr_percentage < 0.7:
                    effort_zones.append('zone2')
                elif hr_percentage < 0.8:
                    effort_zones.append('zone3')
                elif hr_percentage < 0.9:
                    effort_zones.append('zone4')
                else:
                    effort_zones.append('zone5')
            except (ValueError, TypeError, ZeroDivisionError):
                pass
                if hr_percentage < 0.6:
                    effort_zones.append('zone1')
                elif hr_percentage < 0.7:
                    effort_zones.append('zone2')
                elif hr_percentage < 0.8:
                    effort_zones.append('zone3')
                elif hr_percentage < 0.9:
                    effort_zones.append('zone4')
                else:
                    effort_zones.append('zone5')
            except (ValueError, TypeError, ZeroDivisionError):
                pass
        
        return {
            'patterns': patterns if patterns else ['steady_effort'],
            'classification': classify_workout_type(patterns, intervals_count),
            'effort_zones': effort_zones if effort_zones else ['zone2'],
            'intervals_count': intervals_count,
            'analysis_type': 'streams_fallback'
        }
        
    except Exception as e:
        logger.error(f"Streams analysis failed: {str(e)}")
        return analyze_basic_activity_patterns(activity_data)


def analyze_basic_activity_patterns(activity_data: Dict[str, Any]) -> Dict[str, Any]:
    """Basic activity pattern analysis from activity data only"""
    activity_type = activity_data.get('type', 'Activity').lower()
    distance = activity_data.get('distance', 0) / 1000  # km
    duration = activity_data.get('moving_time', 0) / 60  # minutes
    
    # Basic classification based on pace/speed
    classification = 'unknown'
    if activity_type == 'run' and distance > 0 and duration > 0:
        pace_per_km = duration / distance  # minutes per km
        if pace_per_km < 4.0:
            classification = 'speed_work'
        elif pace_per_km < 5.0:
            classification = 'tempo_run'
        elif pace_per_km < 6.0:
            classification = 'moderate_run'
        else:
            classification = 'easy_run'
    
    return {
        'patterns': ['steady_effort'],
        'classification': classification,
        'effort_zones': ['zone2'],
        'intervals_count': 0,
        'analysis_type': 'basic_fallback'
    }


def classify_workout_type(patterns: List[str], intervals_count: int) -> str:
    """Classify workout type based on detected patterns"""
    if 'interval_training' in patterns:
        return 'interval_session'
    elif 'fartlek' in patterns:
        return 'fartlek_run'
    elif intervals_count > 0:
        return 'varied_pace'
    else:
        return 'steady_run'


def extract_module_insights(modules: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Extract insights from processed modules"""
    insights = {}
    
    for module in modules:
        module_name = module.get('name', 'unknown')
        
        if module_name == 'campus_coach':
            # Extract Campus Coach insights
            if 'insight' in module:
                insight_data = module['insight']
                campus_insights = insight_data.get('insights', {})
                
                if campus_insights.get('session_matched', False):
                    insights['campus_coach'] = {
                        'session_match': True,
                        'confidence': insight_data.get('confidence', 0.0),
                        'session_type': campus_insights.get('planned_session', {}).get('session_type', 'unknown'),
                        'performance_analysis': campus_insights.get('performance_analysis', {}),
                        'match_reasons': campus_insights.get('match_reasons', [])
                    }
                else:
                    insights['campus_coach'] = {
                        'session_match': False,
                        'reason': campus_insights.get('match_reasons', ['No match found'])[0] if campus_insights.get('match_reasons') else 'No match found'
                    }
            else:
                # Legacy session matching format
                session_matching = module.get('session_matching', {})
                if session_matching.get('match_found', False):
                    insights['campus_coach'] = {
                        'session_match': True,
                        'confidence': session_matching.get('confidence', 0.0),
                        'session_type': session_matching.get('session_data', {}).get('session_type', 'unknown'),
                        'compliance_analysis': session_matching.get('compliance_analysis', {}),
                        'reasoning': session_matching.get('reasoning', '')
                    }
                else:
                    insights['campus_coach'] = {
                        'session_match': False,
                        'reason': session_matching.get('reason', 'No match found')
                    }
        
        elif module_name == 'enduraw':
            # Extract Enduraw insights
            if 'insight' in module:
                insight_data = module['insight']
                enduraw_insights = insight_data.get('insights', {})
                
                if enduraw_insights.get('enduraw_available', False):
                    insights['enduraw'] = {
                        'enhanced_metrics_available': True,
                        'weather_analysis': enduraw_insights.get('weather_analysis', {}),
                        'enhanced_metrics': enduraw_insights.get('enhanced_metrics', {}),
                        'performance_insights': enduraw_insights.get('performance_insights', {}),
                        'recommendations': enduraw_insights.get('recommendations', []),
                        'processing_time': insight_data.get('metadata', {}).get('enduraw_processing_time')
                    }
                else:
                    insights['enduraw'] = {
                        'enhanced_metrics_available': False,
                        'reason': enduraw_insights.get('error', 'Processing timeout or unavailable')
                    }
            else:
                # Legacy or simple format
                insights['enduraw'] = {
                    'enhanced_metrics_available': True,
                    'note': 'Enduraw processing completed'
                }
    
    return insights


def generate_with_bedrock_enhanced(
    activity_data: Dict[str, Any],
    patterns: Dict[str, Any],
    module_insights: Dict[str, Any]
) -> Dict[str, Any]:
    """Enhanced Bedrock content generation with pattern and module analysis"""
    try:
        # Build enhanced prompt
        prompt = build_enhanced_content_prompt(activity_data, patterns, module_insights)
        
        # Call Bedrock Claude
        bedrock_params = get_bedrock_params()
        response = bedrock.invoke_model(
            modelId=bedrock_params['modelId'],
            body=json.dumps({
                **bedrock_params['body'],
                'messages': [
                    {
                        'role': 'user',
                        'content': prompt
                    }
                ]
            })
        )
        
        # Parse response
        response_body = json.loads(response['body'].read())
        generated_text = response_body['content'][0]['text']
        
        return parse_enhanced_content(generated_text, patterns, module_insights)
        
    except Exception as e:
        logger.error(f"Enhanced Bedrock generation failed: {str(e)}")
        raise


def build_enhanced_content_prompt(
    activity_data: Dict[str, Any],
    patterns: Dict[str, Any],
    module_insights: Dict[str, Any]
) -> str:
    """Build enhanced prompt using embedded prompt system with pattern analysis and module insights"""
    
    # Get the base prompt from embedded prompts - REQUIRED, no fallback
    base_prompt = get_bedrock_content_generation_prompt()
    
    activity_type = activity_data.get('type', 'Activity')
    distance = activity_data.get('distance', 0) / 1000
    duration = activity_data.get('moving_time', 0) / 60
    elevation = activity_data.get('total_elevation_gain', 0)
    
    # Build the complete prompt with base prompt + specific data
    prompt = f"""{base_prompt}

CURRENT TASK: Generate content for this specific activity:

ACTIVITY DATA:
- Type: {activity_type}
- Distance: {distance:.2f} km
- Duration: {duration:.0f} minutes
- Elevation: {elevation:.0f} m
- Original name: {activity_data.get('name', 'Untitled')}

PERFORMANCE ANALYSIS:
- Classification: {patterns.get('classification', 'unknown')}
- Effort patterns: {', '.join(patterns.get('patterns', []))}
- Effort zones: {', '.join(patterns.get('effort_zones', []))}
- Intervals detected: {patterns.get('intervals_count', 0)}
- Analysis type: {patterns.get('analysis_type', 'unknown')}
"""
    
    # Add module insights with enhanced formatting
    if module_insights:
        prompt += "\nMODULE INSIGHTS:\n"
        
        # Campus Coach insights
        if 'campus_coach' in module_insights:
            cc_insights = module_insights['campus_coach']
            if cc_insights.get('session_match', False):
                prompt += f"- Campus Coach: Matched planned {cc_insights.get('session_type', 'session')} "
                prompt += f"(confidence: {cc_insights.get('confidence', 0):.1f})\n"
                if cc_insights.get('performance_analysis'):
                    prompt += f"  Performance: {cc_insights['performance_analysis']}\n"
            else:
                prompt += f"- Campus Coach: No session match ({cc_insights.get('reason', 'unknown')})\n"
        
        # Enduraw insights
        if 'enduraw' in module_insights:
            enduraw_insights = module_insights['enduraw']
            if enduraw_insights.get('enhanced_metrics_available', False):
                prompt += "- Enduraw: Enhanced analytics available\n"
                
                # Weather analysis
                weather = enduraw_insights.get('weather_analysis', {})
                if weather:
                    impact = weather.get('impact_assessment', 'neutral')
                    prompt += f"  Weather impact: {impact}\n"
                
                # Enhanced metrics
                metrics = enduraw_insights.get('enhanced_metrics', {})
                if metrics.get('pace_without_wind'):
                    pace_data = metrics['pace_without_wind']
                    if isinstance(pace_data, dict):
                        wind_adjustment = pace_data.get('wind_adjustment_seconds', 0)
                        try:
                            # Ensure we handle both string and numeric types safely
                            if isinstance(wind_adjustment, str):
                                wind_adjustment_num = float(wind_adjustment) if wind_adjustment.replace('.', '').replace('-', '').isdigit() else 0
                            else:
                                wind_adjustment_num = float(wind_adjustment) if wind_adjustment is not None else 0
                            
                            if wind_adjustment_num > 2:
                                prompt += f"  Wind adjustment: +{wind_adjustment_num:.0f}s/km\n"
                        except (ValueError, TypeError) as e:
                            logger.debug(f"Wind adjustment conversion failed: {e}")
                            # Skip if conversion fails
                            pass
                
                if metrics.get('elevation_cost'):
                    elev_data = metrics['elevation_cost']
                    if isinstance(elev_data, dict):
                        efficiency = elev_data.get('elevation_efficiency', 0)
                        try:
                            efficiency_num = float(efficiency) if efficiency else 0
                            prompt += f"  Elevation efficiency: {efficiency_num:.1%}\n"
                        except (ValueError, TypeError):
                            # Skip if conversion fails
                            pass
                
                # Recommendations
                recommendations = enduraw_insights.get('recommendations', [])
                if recommendations:
                    prompt += f"  Key insight: {recommendations[0]}\n"
            else:
                prompt += f"- Enduraw: {enduraw_insights.get('reason', 'Not available')}\n"
    
    prompt += """
SPECIFIC REQUIREMENTS FOR THIS ACTIVITY:
1. Create a motivational and engaging title (max 50 characters)
2. Write a description that's technical but fun (max 200 words)
3. Use sport-specific terminology
4. Include insights from performance analysis and modules
5. Reference weather/environmental factors if available from Enduraw
6. Mention training session context if Campus Coach match found
7. Maintain an authentic, personal tone that varies from previous activities
8. End the description with "@Generated by Strava AI Boost (Fallback Mode)" on a new line

Return response in JSON format:
{
    "title": "Generated title here",
    "description": "Generated description here\\n\\n@Generated by Strava AI Boost (Fallback Mode)",
    "style_elements": ["motivational", "technical", "weather_aware"],
    "confidence": 0.85
}"""
    
    return prompt


def parse_enhanced_content(
    generated_text: str, 
    patterns: Dict[str, Any], 
    module_insights: Dict[str, Any]
) -> Dict[str, Any]:
    """Parse enhanced content with additional metadata"""
    try:
        # Extract JSON from response
        import re
        json_match = re.search(r'\{.*\}', generated_text, re.DOTALL)
        
        if json_match:
            content_json = json.loads(json_match.group())
            # Add fallback signature to description
            description = content_json.get('description', 'AI-enhanced description')
            if not description.endswith('@Generated by Strava AI Boost (Fallback Mode)'):
                if description.endswith('@Generated by Strava AI Boost'):
                    description = description.replace('@Generated by Strava AI Boost', '@Generated by Strava AI Boost (Fallback Mode)')
                else:
                    description += '\n\n@Generated by Strava AI Boost (Fallback Mode)'
            
            return {
                'title': content_json.get('title', 'Enhanced Activity')[:50],
                'description': description,
                'style_elements': content_json.get('style_elements', ['ai_generated']),
                'confidence': content_json.get('confidence', 0.8),
                'patterns_detected': patterns.get('patterns', []),
                'modules_used': list(module_insights.keys()),
                'analysis_type': patterns.get('analysis_type', 'unknown')
            }
        else:
            # Fallback parsing
            lines = generated_text.strip().split('\n')
            description = '\n'.join(lines[1:]) if len(lines) > 1 else 'AI-enhanced description'
            if not description.endswith('@Generated by Strava AI Boost (Fallback Mode)'):
                if description.endswith('@Generated by Strava AI Boost'):
                    description = description.replace('@Generated by Strava AI Boost', '@Generated by Strava AI Boost (Fallback Mode)')
                else:
                    description += '\n\n@Generated by Strava AI Boost (Fallback Mode)'
            
            return {
                'title': (lines[0] if lines else 'Enhanced Activity')[:50],
                'description': description,
                'style_elements': ['ai_generated'],
                'confidence': 0.7,
                'patterns_detected': patterns.get('patterns', []),
                'modules_used': list(module_insights.keys()),
                'analysis_type': patterns.get('analysis_type', 'unknown')
            }
            
    except Exception as e:
        logger.error(f"Failed to parse enhanced content: {str(e)}")
        return {
            'title': 'Enhanced Activity',
            'description': 'AI-enhanced description',
            'style_elements': ['fallback'],
            'confidence': 0.5,
            'patterns_detected': [],
            'modules_used': [],
            'analysis_type': 'error'
        }



def store_generated_content(activity_id: str, content: Dict[str, Any]) -> None:
    """Store generated content in DynamoDB"""
    try:
        table = dynamodb.Table(ACTIVITIES_TABLE)
        
        # Convert float values to Decimal for DynamoDB compatibility
        def convert_floats_to_decimal(obj):
            """Recursively convert float values to Decimal for DynamoDB"""
            if isinstance(obj, float):
                return Decimal(str(obj))
            elif isinstance(obj, dict):
                return {k: convert_floats_to_decimal(v) for k, v in obj.items()}
            elif isinstance(obj, list):
                return [convert_floats_to_decimal(item) for item in obj]
            else:
                return obj
        
        # Prepare metadata with Decimal conversion
        metadata = {
            'style_elements': content.get('style_elements', []),
            'confidence': convert_floats_to_decimal(content.get('confidence', 0.0)),
            'modules_used': content.get('modules_used', []),
            'patterns_detected': content.get('patterns_detected', []),
            'analysis_type': content.get('analysis_type', 'unknown'),
            'generated_at': datetime.now(timezone.utc).isoformat()
        }
        
        table.update_item(
            Key={'activity_id': activity_id},
            UpdateExpression="SET enhanced_title = :title, enhanced_description = :desc, generation_metadata = :meta",
            ExpressionAttributeValues={
                ':title': content['title'],
                ':desc': content['description'],
                ':meta': metadata
            }
        )
        
        logger.info(f"Stored generated content for activity {activity_id}")
        
    except Exception as e:
        logger.error(f"Failed to store generated content: {str(e)}")
        # Don't raise - content generation succeeded even if storage failed
