"""
Strava Updater Lambda Function

Updates Strava activities with enhanced content generated by AI.
Handles rate limiting and error recovery for Strava API updates.
"""

import json
import os
import logging
from typing import Dict, Any
import boto3
from botocore.exceptions import ClientError
import requests
from datetime import datetime, timedelta

logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Initialize AWS clients
dynamodb = boto3.resource('dynamodb')
secretsmanager = boto3.client('secretsmanager')

# Environment variables
ACTIVITIES_TABLE = os.environ['ACTIVITIES_TABLE']
RATE_LIMITS_TABLE = os.environ['RATE_LIMITS_TABLE']
STRAVA_OAUTH_SECRET = os.environ['STRAVA_OAUTH_SECRET']

# Strava API configuration
STRAVA_API_BASE = "https://www.strava.com/api/v3"


def handler(event: Dict[str, Any], context: Any) -> Dict[str, Any]:
    """
    Lambda handler for updating Strava activities with enhanced content
    
    Updates activity title and description with AI-generated content
    """
    try:
        activity_id = event.get('activity_id')
        user_id = event.get('user_id')
        enhanced_content = event.get('enhanced_content', {})
        
        if not activity_id or not user_id:
            raise ValueError("Missing required parameters: activity_id, user_id")
        
        if not enhanced_content:
            raise ValueError("No enhanced content provided")
        
        logger.info(f"Updating Strava activity {activity_id}")
        
        # Check rate limits before making API call
        if not check_rate_limits():
            raise Exception("Strava API rate limits exceeded")
        
        # Get OAuth tokens
        access_token = get_access_token(user_id)
        
        # Update activity on Strava
        update_result = update_strava_activity(
            activity_id,
            access_token,
            enhanced_content
        )
        
        # Update activity status in DynamoDB
        update_activity_status(activity_id, 'completed', enhanced_content)
        
        # Update rate limit usage
        update_rate_limits(1)  # One API call for update
        
        return {
            'statusCode': 200,
            'activity_id': activity_id,
            'user_id': user_id,
            'update_result': update_result,
            'updated_at': datetime.utcnow().isoformat()
        }
        
    except Exception as e:
        logger.error(f"Strava updater error: {str(e)}")
        
        # Update activity status to failed
        if 'activity_id' in event:
            update_activity_status(event['activity_id'], 'failed', error=str(e))
        
        return {
            'statusCode': 500,
            'error': str(e),
            'activity_id': event.get('activity_id'),
            'user_id': event.get('user_id')
        }


def check_rate_limits() -> bool:
    """Check if we're within Strava API rate limits"""
    try:
        table = dynamodb.Table(RATE_LIMITS_TABLE)
        
        # Check short-term limit (100/15min)
        response = table.get_item(Key={'limit_type': 'short_term'})
        if 'Item' in response:
            usage = response['Item'].get('current_usage', 0)
            reset_time = response['Item'].get('reset_time')
            
            # Check if reset time has passed
            if reset_time and datetime.fromisoformat(reset_time) <= datetime.utcnow():
                # Reset the counter
                table.update_item(
                    Key={'limit_type': 'short_term'},
                    UpdateExpression="SET current_usage = :zero, reset_time = :reset",
                    ExpressionAttributeValues={
                        ':zero': 0,
                        ':reset': (datetime.utcnow() + timedelta(minutes=15)).isoformat()
                    }
                )
                usage = 0
            
            if usage >= 95:  # Leave buffer
                logger.warning(f"Short-term rate limit near threshold: {usage}/100")
                return False
        
        # Check daily limit (1000/day)
        response = table.get_item(Key={'limit_type': 'daily'})
        if 'Item' in response:
            usage = response['Item'].get('current_usage', 0)
            reset_time = response['Item'].get('reset_time')
            
            # Check if reset time has passed
            if reset_time and datetime.fromisoformat(reset_time) <= datetime.utcnow():
                # Reset the counter
                table.update_item(
                    Key={'limit_type': 'daily'},
                    UpdateExpression="SET current_usage = :zero, reset_time = :reset",
                    ExpressionAttributeValues={
                        ':zero': 0,
                        ':reset': (datetime.utcnow() + timedelta(days=1)).isoformat()
                    }
                )
                usage = 0
            
            if usage >= 950:  # Leave buffer
                logger.warning(f"Daily rate limit near threshold: {usage}/1000")
                return False
        
        return True
        
    except Exception as e:
        logger.error(f"Rate limit check error: {str(e)}")
        # Assume we're at limit if we can't check
        return False


def get_access_token(user_id: str) -> str:
    """Get Strava access token from Secrets Manager"""
    try:
        response = secretsmanager.get_secret_value(SecretId=STRAVA_OAUTH_SECRET)
        secrets = json.loads(response['SecretString'])
        
        # For now, use a single token - in production, this would be user-specific
        access_token = secrets.get('access_token')
        
        if not access_token:
            raise ValueError("No access token found in secrets")
        
        # TODO: Check token expiry and refresh if needed
        
        return access_token
        
    except Exception as e:
        logger.error(f"Failed to get access token: {str(e)}")
        raise


def update_strava_activity(
    activity_id: str,
    access_token: str,
    enhanced_content: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Update Strava activity with enhanced content
    
    Updates both title and description with AI-generated content
    """
    try:
        headers = {
            'Authorization': f'Bearer {access_token}',
            'Content-Type': 'application/json'
        }
        
        url = f"{STRAVA_API_BASE}/activities/{activity_id}"
        
        # Prepare update payload
        update_data = {}
        
        if 'title' in enhanced_content and enhanced_content['title']:
            update_data['name'] = enhanced_content['title']
        
        if 'description' in enhanced_content and enhanced_content['description']:
            update_data['description'] = enhanced_content['description']
        
        if not update_data:
            logger.warning("No content to update")
            return {'status': 'no_update_needed'}
        
        logger.info(f"Updating activity {activity_id} with: {list(update_data.keys())}")
        
        # Make API request to update activity
        response = requests.put(
            url,
            headers=headers,
            json=update_data,
            timeout=30
        )
        
        response.raise_for_status()
        
        updated_activity = response.json()
        
        logger.info(f"Successfully updated activity {activity_id}")
        
        return {
            'status': 'success',
            'updated_fields': list(update_data.keys()),
            'activity_name': updated_activity.get('name'),
            'activity_type': updated_activity.get('type')
        }
        
    except requests.exceptions.HTTPError as e:
        if e.response.status_code == 429:
            logger.error("Rate limit exceeded (429)")
            raise Exception("Strava API rate limit exceeded")
        elif e.response.status_code == 401:
            logger.error("Unauthorized (401) - token may be expired")
            raise Exception("Strava API authentication failed")
        else:
            logger.error(f"HTTP error updating activity: {str(e)}")
            raise
    except requests.exceptions.RequestException as e:
        logger.error(f"Request error updating activity: {str(e)}")
        raise
    except Exception as e:
        logger.error(f"Failed to update Strava activity: {str(e)}")
        raise


def update_activity_status(
    activity_id: str,
    status: str,
    enhanced_content: Dict[str, Any] = None,
    error: str = None
) -> None:
    """Update activity processing status in DynamoDB"""
    try:
        table = dynamodb.Table(ACTIVITIES_TABLE)
        
        update_expression = "SET processing_status = :status, updated_at = :timestamp"
        expression_values = {
            ':status': status,
            ':timestamp': datetime.utcnow().isoformat()
        }
        
        if enhanced_content:
            update_expression += ", enhanced_title = :title, enhanced_description = :desc"
            expression_values[':title'] = enhanced_content.get('title', '')
            expression_values[':desc'] = enhanced_content.get('description', '')
            
            if 'modules_used' in enhanced_content:
                update_expression += ", modules_used = :modules"
                expression_values[':modules'] = enhanced_content['modules_used']
        
        if error:
            update_expression += ", error_message = :error"
            expression_values[':error'] = error
        
        table.update_item(
            Key={'activity_id': activity_id},
            UpdateExpression=update_expression,
            ExpressionAttributeValues=expression_values
        )
        
        logger.info(f"Updated activity {activity_id} status to {status}")
        
    except Exception as e:
        logger.error(f"Failed to update activity status: {str(e)}")
        # Don't raise - this is not critical for processing


def update_rate_limits(api_calls_made: int) -> None:
    """Update rate limit counters in DynamoDB"""
    try:
        table = dynamodb.Table(RATE_LIMITS_TABLE)
        current_time = datetime.utcnow()
        
        # Update short-term limit
        table.update_item(
            Key={'limit_type': 'short_term'},
            UpdateExpression="ADD current_usage :calls SET last_request = :time",
            ExpressionAttributeValues={
                ':calls': api_calls_made,
                ':time': current_time.isoformat()
            }
        )
        
        # Update daily limit
        table.update_item(
            Key={'limit_type': 'daily'},
            UpdateExpression="ADD current_usage :calls SET last_request = :time",
            ExpressionAttributeValues={
                ':calls': api_calls_made,
                ':time': current_time.isoformat()
            }
        )
        
        logger.info(f"Updated rate limits: +{api_calls_made} API calls")
        
    except Exception as e:
        logger.error(f"Failed to update rate limits: {str(e)}")
        # Don't raise - rate limit tracking is important but not critical
