/**
 * Runtime configuration loaded from /config.json (generated by setup script)
 * or from Vite env variables during development.
 */

export interface AppConfig {
  apiGatewayUrl: string;
  defaultUserId: string;
  cognitoUserPoolId: string;
  cognitoClientId: string;
  cognitoRegion: string;
  // AgentCore Runtime coach chat (agentic, AG-UI over SSE with tool loops).
  // CoachChat POSTs straight to the AgentCore data plane with a Bearer Cognito
  // JWT; this is the sole coach chat transport (no buffered fallback).
  coachRuntimeArn?: string;
}

let _config: AppConfig | null = null;

export async function loadConfig(): Promise<AppConfig> {
  if (_config) return _config;

  // Try loading from /config.json (production)
  try {
    const res = await fetch('/config.json');
    if (res.ok) {
      _config = await res.json();
      // In dev, route API calls through the Vite proxy (same origin) to bypass CORS.
      if (import.meta.env.DEV && _config) {
        _config = { ..._config, apiGatewayUrl: '' };
      }
      return _config!;
    }
  } catch {
    // Fall through to env vars
  }

  // Fallback to Vite env variables (development)
  _config = {
    apiGatewayUrl: (import.meta.env.VITE_API_GATEWAY_URL as string) || '',
    defaultUserId: (import.meta.env.VITE_DEFAULT_USER_ID as string) || '',
    cognitoUserPoolId: (import.meta.env.VITE_COGNITO_USER_POOL_ID as string) || '',
    cognitoClientId: (import.meta.env.VITE_COGNITO_CLIENT_ID as string) || '',
    cognitoRegion: (import.meta.env.VITE_COGNITO_REGION as string) || 'us-east-1',
    coachRuntimeArn: (import.meta.env.VITE_COACH_RUNTIME_ARN as string) || undefined,
  };

  return _config;
}

export function getConfig(): AppConfig {
  if (!_config) throw new Error('Config not loaded. Call loadConfig() first.');
  return _config;
}
