/**
 * Runtime configuration loaded from /config.json (generated by setup script)
 * or from Vite env variables during development.
 */

export interface AppConfig {
  apiGatewayUrl: string;
  defaultUserId: string;
  cognitoUserPoolId: string;
  cognitoClientId: string;
  cognitoRegion: string;
  // Optional: coach streaming (AG-UI over SSE). When absent, CoachChat falls
  // back to the buffered /coach/ask endpoint — no regression.
  identityPoolId?: string;
  coachStreamUrl?: string;
  // Optional (Phase A): direct AgentCore Runtime coach chat (agentic, AG-UI over
  // SSE with tool loops). When present, CoachChat POSTs straight to the
  // AgentCore data plane with a Bearer Cognito JWT and takes precedence over
  // coachStreamUrl. When absent, the current streaming/buffered paths are used.
  coachRuntimeArn?: string;
}

let _config: AppConfig | null = null;

export async function loadConfig(): Promise<AppConfig> {
  if (_config) return _config;

  // Try loading from /config.json (production)
  try {
    const res = await fetch('/config.json');
    if (res.ok) {
      _config = await res.json();
      // In dev, route API calls through the Vite proxy (same origin) to bypass CORS.
      if (import.meta.env.DEV && _config) {
        _config = { ..._config, apiGatewayUrl: '' };
      }
      return _config!;
    }
  } catch {
    // Fall through to env vars
  }

  // Fallback to Vite env variables (development)
  _config = {
    apiGatewayUrl: (import.meta.env.VITE_API_GATEWAY_URL as string) || '',
    defaultUserId: (import.meta.env.VITE_DEFAULT_USER_ID as string) || '',
    cognitoUserPoolId: (import.meta.env.VITE_COGNITO_USER_POOL_ID as string) || '',
    cognitoClientId: (import.meta.env.VITE_COGNITO_CLIENT_ID as string) || '',
    cognitoRegion: (import.meta.env.VITE_COGNITO_REGION as string) || 'us-east-1',
    identityPoolId: (import.meta.env.VITE_COGNITO_IDENTITY_POOL_ID as string) || undefined,
    coachStreamUrl: (import.meta.env.VITE_COACH_STREAM_URL as string) || undefined,
    coachRuntimeArn: (import.meta.env.VITE_COACH_RUNTIME_ARN as string) || undefined,
  };

  return _config;
}

export function getConfig(): AppConfig {
  if (!_config) throw new Error('Config not loaded. Call loadConfig() first.');
  return _config;
}
