/**
 * Runtime configuration loaded from /config.json (generated by setup script)
 * or from Vite env variables during development.
 */

export interface AppConfig {
  apiGatewayUrl: string;
  apiGatewayKey: string;
  defaultUserId: string;
}

let _config: AppConfig | null = null;

export async function loadConfig(): Promise<AppConfig> {
  if (_config) return _config;

  // Try loading from /config.json (production)
  try {
    const res = await fetch('/config.json');
    if (res.ok) {
      _config = await res.json();
      return _config!;
    }
  } catch {
    // Fall through to env vars
  }

  // Fallback to Vite env variables (development)
  _config = {
    apiGatewayUrl: (import.meta.env.VITE_API_GATEWAY_URL as string) || '',
    apiGatewayKey: (import.meta.env.VITE_API_GATEWAY_KEY as string) || '',
    defaultUserId: (import.meta.env.VITE_DEFAULT_USER_ID as string) || '',
  };

  return _config;
}

export function getConfig(): AppConfig {
  if (!_config) throw new Error('Config not loaded. Call loadConfig() first.');
  return _config;
}
