#!/bin/bash

# Detect AgentCore Agents for Strava AI Boost
# Automatically discovers deployed AgentCore agents and updates environment variables

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# AWS Profile
AWS_PROFILE="your-aws-profile"
AWS_REGION="eu-west-1"

print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to detect AgentCore agents
detect_agentcore_agents() {
    print_status "🔍 Detecting deployed AgentCore agents..."
    
    # Check if AgentCore CLI is available
    if ! command -v agentcore &> /dev/null; then
        print_warning "AgentCore CLI not found. Agents will use fallback mode."
        return 1
    fi
    
    # List all agents
    print_status "Listing AgentCore agents..."
    
    # Get agents list (assuming JSON output)
    AGENTS_JSON=$(agentcore agent list --output json 2>/dev/null || echo "[]")
    
    if [ "$AGENTS_JSON" = "[]" ]; then
        print_warning "No AgentCore agents found"
        return 1
    fi
    
    # Parse agents for Strava AI Boost
    CONTENT_AGENT_ARN=""
    CAMPUS_COACH_AGENT_ARN=""
    
    # Look for content generation agent
    CONTENT_AGENT_ARN=$(echo "$AGENTS_JSON" | jq -r '.[] | select(.name | contains("contentgen") or contains("content")) | .arn' 2>/dev/null | head -1)
    
    # Look for campus coach agent  
    CAMPUS_COACH_AGENT_ARN=$(echo "$AGENTS_JSON" | jq -r '.[] | select(.name | contains("campuscoach") or contains("campus")) | .arn' 2>/dev/null | head -1)
    
    # Output results
    if [ -n "$CONTENT_AGENT_ARN" ] && [ "$CONTENT_AGENT_ARN" != "null" ]; then
        print_success "Found Content Generation Agent: $CONTENT_AGENT_ARN"
        echo "CONTENT_GENERATION_AGENT_ARN=$CONTENT_AGENT_ARN"
    else
        print_warning "Content Generation Agent not found"
        echo "CONTENT_GENERATION_AGENT_ARN="
    fi
    
    if [ -n "$CAMPUS_COACH_AGENT_ARN" ] && [ "$CAMPUS_COACH_AGENT_ARN" != "null" ]; then
        print_success "Found Campus Coach Agent: $CAMPUS_COACH_AGENT_ARN"
        echo "CAMPUS_COACH_AGENT_ARN=$CAMPUS_COACH_AGENT_ARN"
    else
        print_warning "Campus Coach Agent not found"
        echo "CAMPUS_COACH_AGENT_ARN="
    fi
    
    return 0
}

# Function to update CDK context with agent ARNs
update_cdk_context() {
    local content_arn="$1"
    local campus_arn="$2"
    
    print_status "📝 Updating CDK context with agent ARNs..."
    
    # Create or update cdk.context.json
    if [ ! -f "cdk.context.json" ]; then
        echo "{}" > cdk.context.json
    fi
    
    # Update context with agent ARNs
    jq --arg content_arn "$content_arn" --arg campus_arn "$campus_arn" \
       '.agentcore = {
         "content_generation_agent_arn": $content_arn,
         "campus_coach_agent_arn": $campus_arn,
         "agents_detected": true,
         "detection_timestamp": now | strftime("%Y-%m-%dT%H:%M:%SZ")
       }' cdk.context.json > cdk.context.json.tmp && mv cdk.context.json.tmp cdk.context.json
    
    print_success "CDK context updated with agent ARNs"
}

# Function to create environment file for local development
create_env_file() {
    local content_arn="$1"
    local campus_arn="$2"
    
    print_status "📄 Creating .env.agentcore file for local development..."
    
    cat > .env.agentcore << EOF
# AgentCore Agent ARNs - Auto-generated by detect_agentcore_agents.sh
# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Content Generation Agent
CONTENT_GENERATION_AGENT_ARN=$content_arn
CONTENT_GENERATION_AGENT_NAME=$(echo "$content_arn" | sed 's/.*agent\///g' | sed 's/-.*//g')

# Campus Coach Agent  
CAMPUS_COACH_AGENT_ARN=$campus_arn
CAMPUS_COACH_AGENT_NAME=$(echo "$campus_arn" | sed 's/.*agent\///g' | sed 's/-.*//g')

# AgentCore Configuration
AGENTCORE_AGENTS_AVAILABLE=true
AGENTCORE_REGION=$AWS_REGION
EOF

    print_success "Environment file created: .env.agentcore"
}

# Main execution
main() {
    print_status "🚀 Starting AgentCore agent detection for Strava AI Boost..."
    
    # Detect agents
    if detect_agentcore_agents > /tmp/agents_output.txt; then
        # Parse output
        CONTENT_ARN=$(grep "CONTENT_GENERATION_AGENT_ARN=" /tmp/agents_output.txt | cut -d'=' -f2)
        CAMPUS_ARN=$(grep "CAMPUS_COACH_AGENT_ARN=" /tmp/agents_output.txt | cut -d'=' -f2)
        
        # Update CDK context
        update_cdk_context "$CONTENT_ARN" "$CAMPUS_ARN"
        
        # Create environment file
        create_env_file "$CONTENT_ARN" "$CAMPUS_ARN"
        
        print_success "✅ AgentCore agent detection completed successfully"
        print_status "Next steps:"
        print_status "  1. Run 'cdk deploy' to update Lambda environment variables"
        print_status "  2. Source .env.agentcore for local development: source .env.agentcore"
        
    else
        print_warning "⚠️  No AgentCore agents detected"
        print_status "System will use Bedrock fallback mode"
        
        # Create empty context
        update_cdk_context "" ""
        create_env_file "" ""
    fi
    
    # Cleanup
    rm -f /tmp/agents_output.txt
}

# Run main function
main "$@"