#!/bin/bash
# Setup Local Environment Variables for the frontend (Vite dev mode)
# Retrieves API Gateway URL and Cognito config from CloudFormation and creates frontend/.env.local

set -e

PROFILE="${AWS_PROFILE:-your-aws-profile}"
REGION="${AWS_REGION:-us-east-1}"
API_STACK="StravaAIBoost-API"
FRONTEND_STACK="StravaAIBoost-Frontend"

echo "🔧 Setting up local environment variables..."
echo ""

get_output() {
    aws cloudformation describe-stacks \
        --stack-name "$1" \
        --profile "$PROFILE" \
        --region "$REGION" \
        --query "Stacks[0].Outputs[?starts_with(OutputKey, \`$2\`)].OutputValue | [0]" \
        --output text
}

echo "📡 Retrieving API Gateway URL..."
API_URL=$(get_output "$API_STACK" "StravaAIBoostAPIEndpoint")
if [ -z "$API_URL" ] || [ "$API_URL" = "None" ]; then
    echo "❌ Failed to retrieve API Gateway URL"
    exit 1
fi
echo "✅ API Gateway URL: $API_URL"

echo "🔐 Retrieving Cognito configuration..."
USER_POOL_ID=$(get_output "$FRONTEND_STACK" "UserPoolId")
CLIENT_ID=$(get_output "$FRONTEND_STACK" "UserPoolClientId")
IDENTITY_POOL_ID=$(get_output "$API_STACK" "CoachIdentityPoolId")
COACH_STREAM_URL=$(get_output "$API_STACK" "CoachStreamUrl")
echo "✅ Cognito User Pool: $USER_POOL_ID"

ENV_FILE="frontend/.env.local"
echo "📝 Creating $ENV_FILE..."

cat > "$ENV_FILE" << EOF
# Strava AI Boost Frontend Configuration (Vite dev mode)
# Generated by scripts/setup_local_env.sh on $(date)

VITE_API_GATEWAY_URL=$API_URL
VITE_COGNITO_USER_POOL_ID=$USER_POOL_ID
VITE_COGNITO_CLIENT_ID=$CLIENT_ID
VITE_COGNITO_REGION=$REGION
VITE_COGNITO_IDENTITY_POOL_ID=$IDENTITY_POOL_ID
VITE_COACH_STREAM_URL=${COACH_STREAM_URL}coach/ask/stream

# User Configuration (set via Strava OAuth connection, or override manually)
VITE_DEFAULT_USER_ID=${DEFAULT_USER_ID:-}
EOF

echo "✅ Environment file created: $ENV_FILE"
echo ""
echo "🎯 Next steps:"
echo "  1. cd frontend"
echo "  2. npm run dev"
echo "  3. Open http://localhost:5173"
echo ""
echo "✨ Setup complete!"
