#!/bin/bash
# Setup Local Environment Variables for Flask App
# This script retrieves API Gateway URL and API Key from AWS and creates a .env file

set -e

PROFILE="your-aws-profile"
REGION="eu-west-1"
STACK_NAME="StravaAIBoost-API"

echo "🔧 Setting up local environment variables..."
echo ""

# Get API Gateway URL from CloudFormation
echo "📡 Retrieving API Gateway URL..."
API_URL=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --profile "$PROFILE" \
    --region "$REGION" \
    --query 'Stacks[0].Outputs[?OutputKey==`StravaAIBoostAPIEndpoint7FE86F78`].OutputValue' \
    --output text)

if [ -z "$API_URL" ]; then
    echo "❌ Failed to retrieve API Gateway URL"
    exit 1
fi

echo "✅ API Gateway URL: $API_URL"

# Get API Key ID from CloudFormation
echo "🔑 Retrieving API Key..."
API_KEY_ID=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --profile "$PROFILE" \
    --region "$REGION" \
    --query 'Stacks[0].Outputs[?OutputKey==`APIKeyValue`].OutputValue' \
    --output text)

if [ -z "$API_KEY_ID" ]; then
    echo "❌ Failed to retrieve API Key ID"
    exit 1
fi

# Get API Key value
API_KEY=$(aws apigateway get-api-key \
    --api-key "$API_KEY_ID" \
    --include-value \
    --profile "$PROFILE" \
    --region "$REGION" \
    --query 'value' \
    --output text)

if [ -z "$API_KEY" ]; then
    echo "❌ Failed to retrieve API Key value"
    exit 1
fi

echo "✅ API Key retrieved"

# Create .env file in local_interface directory
ENV_FILE="local_interface/.env"

echo "📝 Creating $ENV_FILE..."

cat > "$ENV_FILE" << EOF
# Strava AI Boost Local Interface Configuration
# Generated by scripts/setup_local_env.sh on $(date)

# API Gateway Configuration
API_GATEWAY_URL=$API_URL
API_GATEWAY_KEY=$API_KEY

# AWS Configuration
AWS_REGION=$REGION
AWS_PROFILE=$PROFILE

# User Configuration
DEFAULT_USER_ID=YOUR_USER_ID
EOF

echo "✅ Environment file created: $ENV_FILE"
echo ""
echo "🎯 Next steps:"
echo "  1. cd local_interface"
echo "  2. python app.py"
echo "  3. Open http://localhost:3000"
echo ""
echo "✨ Setup complete!"
