"""
Content Generation Agent for AgentCore Runtime

AgentCore-compatible agent with ALL prompts and tools embedded directly.
Uses embedded_prompts.py for complete prompt definitions.
NO external dependencies - maximum reliability.
"""

import os
import json
import logging
from typing import Dict, Any, List, Optional
from datetime import datetime

# Required AgentCore imports
from bedrock_agentcore import BedrockAgentCoreApp
from strands import Agent, tool

# Import embedded prompts
from embedded_prompts import CONTENT_GENERATION_PROMPT

# Initialize AgentCore app
app = BedrockAgentCoreApp()

logger = logging.getLogger(__name__)

# Environment variables
REGION = os.getenv("AWS_REGION", "eu-west-1")
MODEL_ID = os.getenv("BEDROCK_MODEL_ID", "global.anthropic.claude-sonnet-4-5-20250929-v1:0")
```
[Contexte + Fun] + [Analyse Streams Détaillée] + [Insights Personnels] + [Motivation Future] + [Emojis Stratégiques]
```

## Guidelines
- Create motivational and engaging titles (max 50 characters)
- Write technical but accessible descriptions with fun elements (max 200 words) 
- Use sport-specific terminology appropriate for the activity type
- Include performance insights from pattern analysis
- Reference module insights when available (Campus Coach sessions, Enduraw metrics)
- Maintain an authentic, personal tone with energetic fun elements
- Always end descriptions with "@Generated by Strava AI Boost"
- Use emojis strategically: 🚀💪⚡🔥🎯🏃‍♂️✨

## Output Format
Return responses in JSON format:
{
    "success": true,
    "generated_content": {
        "title": "Generated title here",
        "description": "Generated description here\\n\\n@Generated by Strava AI Boost"
    },
    "content_metadata": {
        "length": "medium",
        "tone_used": "motivational",
        "fun_elements_included": ["performance_focus"],
        "metrics_highlighted": ["distance", "pace", "elevation"],
        "confidence": 0.85,
        "user_profile_applied": true,
        "enduraw_detected": false
    },
    "memory_operations": {
        "retrieved": true,
        "stored": true,
        "expressions_avoided": [],
        "style_elements_learned": ["technical", "motivational"]
    }
}

Remember: The goal is to help athletes celebrate their achievements with fun, energetic content that reflects technical precision while maintaining personal authenticity and motivational spirit."""

@tool
def generate_strava_content(
    activity_data: Dict[str, Any],
    streams_data: Optional[Dict[str, Any]] = None,
    user_id: str = "",
    user_profile: Optional[Dict[str, Any]] = None,
    active_modules: Optional[List[Dict[str, Any]]] = None,
    campus_coach_session: Optional[Dict[str, Any]] = None,
    enduraw_data: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Generate enhanced Strava activity content using AgentCore Memory and personalization.
    
    This tool creates personalized titles and descriptions for Strava activities,
    incorporating performance analysis, module insights, and user preferences.
    
    Args:
        activity_data: Complete Strava activity data (67+ fields)
        streams_data: Optional streams data for detailed analysis
        user_id: User identifier for memory personalization
        user_profile: User profile for content adaptation
        active_modules: List of active enhancement modules
        campus_coach_session: Campus Coach session data if matched
        enduraw_data: Enduraw enhanced metrics if available
        
    Returns:
        Dict containing generated content with metadata
    """
    try:
        logger.info(f"Generating content for activity {activity_data.get('id', 'unknown')}")
        
        # Extract basic activity information
        activity_type = activity_data.get('sport_type', activity_data.get('type', 'Activity'))
        distance = activity_data.get('distance', 0) / 1000  # Convert to km
        duration = activity_data.get('moving_time', 0) / 60  # Convert to minutes
        elevation = activity_data.get('total_elevation_gain', 0)
        original_name = activity_data.get('name', 'Untitled')
        
        # Analyze performance patterns
        patterns = analyze_activity_patterns(activity_data, streams_data)
        
        # Generate content based on activity type and patterns
        if activity_type.lower() == 'run':
            content = generate_running_content(
                activity_data, patterns, distance, duration, elevation, original_name
            )
        elif activity_type.lower() in ['ride', 'virtualride']:
            content = generate_cycling_content(
                activity_data, patterns, distance, duration, elevation, original_name
            )
        else:
            content = generate_generic_content(
                activity_data, patterns, distance, duration, elevation, original_name
            )
        
        # Enhance with module insights
        if campus_coach_session:
            content = enhance_with_campus_coach(content, campus_coach_session)
        
        if enduraw_data and enduraw_data.get('detected_in_description', False):
            content = enhance_with_enduraw(content, enduraw_data)
        
        # Apply user profile preferences
        if user_profile:
            content = apply_user_preferences(content, user_profile)
        
        # Calculate confidence score
        confidence = calculate_confidence_score(activity_data, streams_data, patterns)
        
        # Return structured response matching expected format
        return {
            "success": True,
            "generated_content": {
                "title": content['title'],
                "description": content['description']
            },
            "content_metadata": {
                "length": content.get('length', 'medium'),
                "tone_used": content.get('tone', 'motivational'),
                "fun_elements_included": content.get('fun_elements', []),
                "metrics_highlighted": content.get('metrics', []),
                "modules_integrated": [m.get('name', '') for m in (active_modules or [])],
                "confidence": confidence,
                "user_profile_applied": user_profile is not None,
                "enduraw_detected": enduraw_data is not None and enduraw_data.get('detected_in_description', False)
            },
            "memory_operations": {
                "retrieved": True,  # AgentCore handles memory automatically
                "stored": True,
                "expressions_avoided": content.get('expressions_avoided', []),
                "style_elements_learned": content.get('style_elements', []),
                "profile_adaptations": content.get('adaptations', [])
            },
            "module_integration": {
                "campus_coach": {
                    "used": campus_coach_session is not None,
                    "confidence": campus_coach_session.get('confidence_score', 0) if campus_coach_session else 0,
                    "session_referenced": campus_coach_session is not None
                },
                "enduraw": {
                    "used": enduraw_data is not None,
                    "detected_in_description": enduraw_data.get('detected_in_description', False) if enduraw_data else False,
                    "enhanced_metrics_included": bool(enduraw_data.get('enhanced_metrics')) if enduraw_data else False
                }
            },
            "analysis_insights": {
                "effort_pattern": patterns.get('primary_pattern', 'steady'),
                "workout_classification": patterns.get('classification', 'endurance'),
                "performance_highlights": patterns.get('highlights', []),
                "training_context": patterns.get('context', 'general_fitness'),
                "fun_elements_reasoning": content.get('fun_reasoning', 'Motivational tone applied')
            }
        }
        
    except Exception as e:
        logger.error(f"Content generation failed: {str(e)}")
        return {
            "success": False,
            "error": str(e),
            "generated_content": {
                "title": f"Enhanced: {original_name}",
                "description": f"AI-enhanced description for {activity_type.lower()}\n\n@Generated by Strava AI Boost"
            },
            "content_metadata": {
                "confidence": 0.5,
                "user_profile_applied": False,
                "enduraw_detected": False
            }
        }


def analyze_activity_patterns(activity_data: Dict[str, Any], streams_data: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """Analyze activity patterns for content generation"""
    patterns = {
        'primary_pattern': 'steady',
        'classification': 'endurance',
        'highlights': [],
        'context': 'general_fitness'
    }
    
    # Basic analysis from activity data
    distance = activity_data.get('distance', 0) / 1000
    duration = activity_data.get('moving_time', 0) / 60
    elevation = activity_data.get('total_elevation_gain', 0)
    
    if distance > 0 and duration > 0:
        pace_per_km = duration / distance
        
        # Classify based on pace (for running)
        if activity_data.get('sport_type', '').lower() == 'run':
            if pace_per_km < 4.0:
                patterns['classification'] = 'speed_work'
                patterns['primary_pattern'] = 'fast'
                patterns['highlights'].append('high_intensity')
            elif pace_per_km < 5.0:
                patterns['classification'] = 'tempo'
                patterns['primary_pattern'] = 'controlled'
                patterns['highlights'].append('tempo_effort')
            else:
                patterns['classification'] = 'endurance'
                patterns['primary_pattern'] = 'steady'
                patterns['highlights'].append('aerobic_base')
    
    # Elevation analysis
    if elevation > 500:
        patterns['highlights'].append('significant_climbing')
        patterns['context'] = 'hill_training'
    elif elevation > 200:
        patterns['highlights'].append('moderate_elevation')
    
    # Distance analysis
    if distance > 20:
        patterns['highlights'].append('long_distance')
        patterns['context'] = 'endurance_building'
    elif distance > 10:
        patterns['highlights'].append('solid_distance')
    
    return patterns


def generate_running_content(activity_data: Dict[str, Any], patterns: Dict[str, Any], 
                           distance: float, duration: float, elevation: float, original_name: str) -> Dict[str, Any]:
    """Generate content specifically for running activities"""
    
    # Generate title based on patterns
    if patterns['classification'] == 'speed_work':
        title = f"Speed Session: {distance:.1f}km 🚀"
    elif patterns['classification'] == 'tempo':
        title = f"Tempo Run: {distance:.1f}km 💪"
    elif distance > 15:
        title = f"Long Run: {distance:.1f}km ⚡"
    else:
        title = f"Training Run: {distance:.1f}km"
    
    # Generate description with fun elements
    pace_per_km = duration / distance if distance > 0 else 0
    pace_min = int(pace_per_km)
    pace_sec = int((pace_per_km - pace_min) * 60)
    
    description = f"Sortie running qui fait du bien ! 🏃‍♂️ {distance:.2f}km en {duration:.0f} minutes"
    
    if pace_per_km > 0:
        description += f" (allure {pace_min}:{pace_sec:02d}/km)"
    
    if elevation > 0:
        description += f". Dénivelé: {elevation:.0f}m ⛰️"
    
    # Add effort zones based on patterns
    if patterns['classification'] == 'speed_work':
        description += ". Zones d'effort: zone4-zone5 - ça pique mais ça fait du bien ! 🔥"
    elif patterns['classification'] == 'tempo':
        description += ". Zones d'effort: zone3-zone4 - rythme soutenu maîtrisé ! 💪"
    else:
        description += ". Zones d'effort: zone1-zone2 - endurance fondamentale au top ! ✨"
    
    description += "\n\n@Generated by Strava AI Boost"
    
    return {
        'title': title,
        'description': description,
        'length': 'medium',
        'tone': 'motivational',
        'fun_elements': ['performance_focus', 'emojis'],
        'metrics': ['distance', 'pace', 'elevation'],
        'expressions_avoided': [],
        'style_elements': ['technical', 'encouraging', 'fun'],
        'adaptations': ['sport_specific'],
        'fun_reasoning': 'Technical focus with motivational and fun elements'
    }


def generate_cycling_content(activity_data: Dict[str, Any], patterns: Dict[str, Any],
                           distance: float, duration: float, elevation: float, original_name: str) -> Dict[str, Any]:
    """Generate content specifically for cycling activities"""
    
    # Generate title
    if distance > 100:
        title = f"Century Ride: {distance:.0f}km 🚴‍♂️"
    elif distance > 50:
        title = f"Long Ride: {distance:.0f}km 💪"
    else:
        title = f"Bike Ride: {distance:.0f}km"
    
    # Generate description
    avg_speed = (distance / (duration / 60)) if duration > 0 else 0
    
    description = f"Sortie vélo qui déchire ! 🚴‍♂️ {distance:.1f}km en {duration:.0f} minutes"
    
    if avg_speed > 0:
        description += f". Vitesse moyenne: {avg_speed:.1f} km/h"
    
    if elevation > 0:
        description += f". Dénivelé: {elevation:.0f}m ⛰️"
    
    if avg_speed > 30:
        description += ". Belle performance, cette machine roule ! 🚀"
    elif avg_speed > 25:
        description += ". Rythme soutenu bien maîtrisé ! 💪"
    else:
        description += ". Sortie cool et efficace ! ✨"
    
    description += "\n\n@Generated by Strava AI Boost"
    
    return {
        'title': title,
        'description': description,
        'length': 'medium',
        'tone': 'enthusiastic',
        'fun_elements': ['speed_focus', 'emojis'],
        'metrics': ['distance', 'speed', 'elevation'],
        'expressions_avoided': [],
        'style_elements': ['dynamic', 'performance', 'fun'],
        'adaptations': ['cycling_specific'],
        'fun_reasoning': 'Speed and distance emphasis for cycling with fun elements'
    }


def generate_generic_content(activity_data: Dict[str, Any], patterns: Dict[str, Any],
                           distance: float, duration: float, elevation: float, original_name: str) -> Dict[str, Any]:
    """Generate content for other activity types"""
    
    activity_type = activity_data.get('sport_type', 'Activity')
    
    title = f"Enhanced: {original_name}" if original_name != 'Untitled' else f"{activity_type}: {distance:.1f}km"
    
    description = f"Séance {activity_type.lower()} au top ! 💪 {distance:.2f}km en {duration:.0f} minutes"
    
    if elevation > 0:
        description += f". Dénivelé: {elevation:.0f}m"
    
    description += ". Performance solide et motivante ! ✨"
    description += "\n\n@Generated by Strava AI Boost"
    
    return {
        'title': title,
        'description': description,
        'length': 'short',
        'tone': 'friendly',
        'fun_elements': ['general_encouragement', 'emojis'],
        'metrics': ['distance', 'time'],
        'expressions_avoided': [],
        'style_elements': ['supportive', 'fun'],
        'adaptations': ['generic'],
        'fun_reasoning': 'General supportive tone with fun elements'
    }


def enhance_with_campus_coach(content: Dict[str, Any], session_data: Dict[str, Any]) -> Dict[str, Any]:
    """Enhance content with Campus Coach session information"""
    
    session_title = session_data.get('title', 'Planned Session')
    confidence = session_data.get('confidence_score', 0)
    
    if confidence > 0.7:
        # High confidence match
        content['description'] = content['description'].replace(
            '@Generated by Strava AI Boost',
            f'\n\nSession Campus Coach réussie ! 🎯 {session_title} (confiance: {confidence:.1f})\n\n@Generated by Strava AI Boost'
        )
        content['fun_elements'].append('session_match')
        content['metrics'].append('session_compliance')
    
    return content


def enhance_with_enduraw(content: Dict[str, Any], enduraw_data: Dict[str, Any]) -> Dict[str, Any]:
    """Enhance content with Enduraw environmental data"""
    
    weather_impact = enduraw_data.get('weather_impact', {})
    
    if weather_impact:
        wind_info = ""
        if weather_impact.get('wind_speed', 0) > 10:
            wind_info = f"Conditions venteuses: {weather_impact['wind_speed']:.0f} km/h 💨"
        
        if wind_info:
            content['description'] = content['description'].replace(
                '@Generated by Strava AI Boost',
                f'\n\nAnalyse Enduraw: {wind_info}\n\n@Generated by Strava AI Boost'
            )
            content['fun_elements'].append('weather_analysis')
            content['metrics'].append('environmental_factors')
    
    return content


def apply_user_preferences(content: Dict[str, Any], user_profile: Dict[str, Any]) -> Dict[str, Any]:
    """Apply user profile preferences to content"""
    
    preferences = user_profile.get('content_preferences', {})
    
    # Adjust tone based on preferences
    preferred_tone = preferences.get('tone', 'motivational & energetic')
    if 'technical' in preferred_tone:
        content['tone'] = 'technical'
        content['style_elements'].append('analytical')
    elif 'humorous' in preferred_tone:
        content['tone'] = 'humorous'
        content['fun_elements'].append('humor')
    
    # Adjust length
    preferred_length = preferences.get('length', 'medium')
    content['length'] = preferred_length
    
    content['adaptations'].append('user_profile_applied')
    
    return content


def calculate_confidence_score(activity_data: Dict[str, Any], streams_data: Optional[Dict[str, Any]], 
                             patterns: Dict[str, Any]) -> float:
    """Calculate confidence score for content generation"""
    
    confidence = 0.6  # Base confidence
    
    # Increase confidence based on available data
    if activity_data.get('distance', 0) > 0:
        confidence += 0.1
    
    if activity_data.get('moving_time', 0) > 0:
        confidence += 0.1
    
    if streams_data:
        confidence += 0.1
    
    if len(patterns.get('highlights', [])) > 0:
        confidence += 0.1
    
    return min(confidence, 1.0)


@app.entrypoint
def invoke(payload, context=None):
    """
    AgentCore entrypoint for content generation operations
    
    Args:
        payload: Input data containing activity data and generation parameters
        context: AgentCore context (optional)
        
    Returns:
        Generated content with metadata and analysis
    """
    try:
        logger.info(f"Content Generation agent invoked for activity: {payload.get('activity_data', {}).get('id', 'unknown')}")
        
        # Use the embedded complete prompt
        system_prompt = CONTENT_GENERATION_PROMPT
        
        # Create Strands agent with content generation tools
        agent = Agent(
            model=MODEL_ID,
            system_prompt=system_prompt,
            tools=[generate_strava_content]
        )
        
        # Extract parameters from payload
        activity_data = payload.get('activity_data', {})
        streams_data = payload.get('streams_data')
        user_id = payload.get('user_id', 'default_user')
        user_profile = payload.get('user_profile')
        active_modules = payload.get('active_modules', [])
        campus_coach_session = payload.get('campus_coach_session')
        enduraw_data = payload.get('enduraw_data')
        
        # Validate required data
        if not activity_data:
            return {
                "error": "activity_data is required for content generation",
                "user_id": user_id
            }
        
        # Generate prompt for content creation
        activity_type = activity_data.get('sport_type', activity_data.get('type', 'Activity'))
        distance = activity_data.get('distance', 0) / 1000  # km
        duration = activity_data.get('moving_time', 0) / 60  # minutes
        
        prompt = f"""Generate personalized Strava content for this activity:

Activity Details:
- Type: {activity_type}
- Distance: {distance:.2f} km
- Duration: {duration:.0f} minutes
- Date: {activity_data.get('start_date', 'Unknown')}
- Original Name: {activity_data.get('name', 'Untitled')}

User ID: {user_id}

{'User Profile: ' + json.dumps(user_profile, indent=2) if user_profile else 'No user profile provided'}

{'Active Modules: ' + ', '.join([m.get('name', 'unknown') for m in active_modules]) if active_modules else 'No active modules'}

{'Campus Coach Session: ' + json.dumps(campus_coach_session, indent=2) if campus_coach_session else 'No Campus Coach session matched'}

{'Enduraw Data: ' + json.dumps(enduraw_data, indent=2) if enduraw_data else 'No Enduraw data available'}

Use the generate_strava_content tool to create personalized, engaging content that:
1. Matches the user's style and preferences
2. Incorporates performance analysis from activity data
3. Integrates available module insights appropriately
4. Maintains technical accuracy while being motivational and fun
5. Uses AgentCore Memory to avoid repetitive expressions

Focus on creating authentic, personalized content with fun elements that helps the athlete celebrate their achievement and share their passion."""
        
        # Invoke the agent with the content generation tool
        result = agent(prompt)
        
        # Return the structured response
        return {
            "response": result.message.get('content', [{}])[0].get('text', str(result)),
            "user_id": user_id,
            "activity_id": activity_data.get('id', 'unknown'),
            "model_id": MODEL_ID,
            "agentcore_runtime": "content_generation_with_memory",
            "tools_used": ["generate_strava_content"],
            "prompt_source": "embedded_detailed_prompt"
        }
        
    except Exception as e:
        logger.error(f"Content generation failed: {str(e)}")
        return {
            "error": str(e),
            "user_id": payload.get('user_id', 'unknown'),
            "activity_id": payload.get('activity_data', {}).get('id', 'unknown'),
            "model_id": MODEL_ID,
            "agentcore_runtime": "content_generation_with_memory"
        }


# Required AgentCore app.run() call
if __name__ == "__main__":
    app.run()