"""Unit tests for the reprocess feedback-loop fix.

On a reprocess, Strava's current description IS our own generated output. Feeding
it back as the athlete's "original" text let a generation mangle
("split squat 2 kettlebells de 20kg" -> "20 fentes bulgares") propagate forever.
These tests lock the two guards that break the loop while still honoring a manual
edit the athlete makes on Strava.
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'lambda_functions'))

from processing.activity_fetcher import _looks_generated, _resolve_original_text
from processing.content_generator import _apply_preserved_original


class TestLooksGenerated:
    def test_signed_text_is_generated(self):
        assert _looks_generated("Bloc 1 ...\n@Generated by Strava AI Boost")
        assert _looks_generated("...\n📊 Strava AI Boost Coach\n...")

    def test_plain_text_not_generated(self):
        assert not _looks_generated("Renfo course a pied Campus, mollet 12kg")
        assert not _looks_generated("")
        assert not _looks_generated(None)


class TestResolveOriginalText:
    def test_generated_fetch_preserves_stored_original(self):
        # Reprocess: Strava desc is our signed output -> keep the stored true original
        fetched = "Séance Campus validée ...\n@Generated by Strava AI Boost"
        stored = {
            "original_description": "Renfo mollet 12kg, split squat 2 kettlebells de 20kg, swing 24kg",
            "original_name": "Renfo bas du corps",
        }
        desc, name = _resolve_original_text(fetched, "Renfo - Cycle Endurance de Force", stored)
        assert desc == stored["original_description"]
        assert name == "Renfo bas du corps"

    def test_manual_edit_without_signature_is_honored(self):
        # Athlete edited the Strava description by hand -> that edit wins
        fetched = "Ma vraie description editee a la main, mollet 14kg"
        desc, name = _resolve_original_text(fetched, "Mon titre", {"original_description": "old stored"})
        assert desc == fetched
        assert name == "Mon titre"

    def test_both_generated_keeps_fetched(self):
        # True original already lost (stored is also generated) -> no clean source
        fetched = "x\n@Generated by Strava AI Boost"
        stored = {"original_description": "y\nStrava AI Boost Coach"}
        desc, _name = _resolve_original_text(fetched, "t", stored)
        assert desc == fetched

    def test_no_existing_item_keeps_fetched(self):
        fetched = "x\n@Generated by Strava AI Boost"
        desc, name = _resolve_original_text(fetched, "t", None)
        assert desc == fetched
        assert name == "t"


class TestApplyPreservedOriginal:
    def test_override_with_preserved(self):
        activity_data = {"description": "current generated text", "name": "gen title"}
        _apply_preserved_original(
            activity_data,
            {"original_description": "true original, split squat 2x20kg", "original_name": "true title"},
        )
        assert activity_data["description"] == "true original, split squat 2x20kg"
        assert activity_data["name"] == "true title"

    def test_no_preserved_leaves_unchanged(self):
        activity_data = {"description": "current", "name": "cur"}
        _apply_preserved_original(activity_data, {})
        assert activity_data["description"] == "current"
        assert activity_data["name"] == "cur"
